// Copyright (C) 2015 The Gravitee team (http://gravitee.io)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Command crdgen amends an OpenAPI spec shipped in a Go module so that
// oapi-codegen generates CRD-ready structs from it: it applies overlays,
// drops read-only properties and writes kubebuilder markers into descriptions.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gravitee-io/gravitee-kubernetes-operator/hack/crdgen/amend"
	"github.com/speakeasy-api/openapi/overlay/loader"
	"gopkg.in/yaml.v3"
)

const header = "# Code generated by crdgen. DO NOT EDIT.\n"

type stringList []string

func (s *stringList) String() string { return strings.Join(*s, ",") }

func (s *stringList) Set(v string) error {
	*s = append(*s, v)
	return nil
}

func main() {
	var overlays stringList
	module := flag.String("module", "", "Go module path shipping the spec")
	spec := flag.String("spec", "", "path of the spec inside the module")
	out := flag.String("out", "", "path of the amended spec")
	flag.Var(&overlays, "overlay", "overlay to apply, in order (repeatable)")
	flag.Parse()

	if err := run(*module, *spec, overlays, *out); err != nil {
		fmt.Fprintln(os.Stderr, "crdgen:", err)
		os.Exit(1)
	}
}

func run(module, spec string, overlays []string, out string) error {
	dir, err := moduleDir(module)
	if err != nil {
		return err
	}
	node, err := loader.LoadSpecification(filepath.Join(dir, spec))
	if err != nil {
		return err
	}
	for _, path := range overlays {
		if err := applyOverlay(node, path); err != nil {
			return err
		}
	}
	doc, err := load(node)
	if err != nil {
		return err
	}
	if err := amend.Normalize(doc); err != nil {
		return err
	}
	amend.Infer(doc)
	if err := amend.ApplyExtensions(doc); err != nil {
		return err
	}
	amend.FlattenInlineEnums(doc)
	return write(doc, out)
}

// moduleDir downloads module at the version go.mod requires, when it is not in the module
// cache yet (a fresh CI cache), and returns its directory.
func moduleDir(module string) (string, error) {
	cmd := exec.Command("go", "mod", "download", "-json", module)
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("downloading module %s: %w", module, err)
	}
	var downloaded struct{ Dir string }
	if err := json.Unmarshal(out, &downloaded); err != nil {
		return "", fmt.Errorf("reading module %s download: %w", module, err)
	}
	if downloaded.Dir == "" {
		return "", fmt.Errorf("module %s has no directory in the module cache", module)
	}
	return downloaded.Dir, nil
}

func applyOverlay(node *yaml.Node, path string) error {
	o, err := loader.LoadOverlay(path)
	if err != nil {
		return err
	}
	if err := o.Validate(); err != nil {
		return fmt.Errorf("overlay %s: %w", path, err)
	}
	if warnings, err := o.ApplyToStrict(node); err != nil {
		return fmt.Errorf("overlay %s: %w\n- %s", path, err, strings.Join(warnings, "\n- "))
	}
	return nil
}

func load(node *yaml.Node) (*openapi3.T, error) {
	data, err := yaml.Marshal(node)
	if err != nil {
		return nil, err
	}
	return openapi3.NewLoader().LoadFromData(data)
}

func write(doc *openapi3.T, out string) error {
	var buf bytes.Buffer
	buf.WriteString(header)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return err
	}
	return os.WriteFile(out, buf.Bytes(), 0o600)
}
