#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: gravitee.io/v1alpha1
kind: ApiV4Definition
metadata:
  name: api-v4-native-with-context
spec:
  contextRef:
    name: "dev-ctx"
  name: "api-v4-native-with-context"
  description: "V4 Native API managed by Gravitee Kubernetes Operator 2"
  version: "1.0"
  type: NATIVE
  state: STARTED
  listeners:
    - type: KAFKA
      host: "kafka.local.2"
      port: 9092
      entrypoints:
        - type: native-kafka
  endpointGroups:
    - name: Default Native endpoint group
      type: native-kafka
      sharedConfiguration:
        security:
          protocol: PLAINTEXT
      endpoints:
        - name: Default Native proxy
          type: native-kafka
          inheritConfiguration: true
          "weight": 1
          configuration:
            bootstrapServers: "kafka.local:9001"
          secondary: false
  plans:
    KeyLess:
      name: "Free plan"
      description: "This plan does not require any authentication"
      security:
        type: "KEY_LESS"
  pages:
    markdowns-folder:
      name: markdowns
      type: FOLDER
    markdown:
      name: "hello-markdown"
      type: MARKDOWN
      parent: markdowns-folder
      content: |
        Hello world!
        --
        This is markdown.
      visibility: PRIVATE
