#!/bin/sh

if ! type bin/commitlint >/dev/null 2>/dev/null; then
	echo ""
    echo "bin/commitlint could not be found"
    echo "try again after installing commitlint or add commitlint to PATH"
	echo ""
    exit 2;
fi

bin/commitlint lint --message $1

