// Package identityprovider provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package identityprovider

import (
	"github.com/gravitee-io/gravitee-kubernetes-operator/api/model/refs"
	"github.com/gravitee-io/gravitee-kubernetes-operator/api/model/utils"
)

// AutomationIdentityProvider An identity provider managed under a domain by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update.
// +kubebuilder:validation:XValidation:rule="(has(self.system) && self.system) || (has(self.name) && has(self.type) && has(self.configuration))",message="name, type and configuration are required unless system is true"
// +kubebuilder:validation:XValidation:rule="has(self.type) == has(oldSelf.type) && (!has(self.type) || self.type == oldSelf.type)",message="type is immutable"
type AutomationIdentityProvider = IdentityProvider

// IdentityProvider An identity provider managed under a domain by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update.
// +kubebuilder:validation:XValidation:rule="(has(self.system) && self.system) || (has(self.name) && has(self.type) && has(self.configuration))",message="name, type and configuration are required unless system is true"
// +kubebuilder:validation:XValidation:rule="has(self.type) == has(oldSelf.type) && (!has(self.type) || self.type == oldSelf.type)",message="type is immutable"
type IdentityProvider struct {
	// Configuration Plugin-specific configuration as a JSON-encoded string. Its shape is defined by the selected identity provider type. Sensitive values, as flagged by the plugin, are returned as ******** in every response; an unset sensitive value is omitted. Sending ******** back on update keeps the stored value; sending it on create is rejected.
	// +kubebuilder:validation:Optional
	Configuration *utils.GenericStringMap `json:"configuration,omitempty"`

	// DomainRef Domain CRD reference
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="domainRef is immutable"
	// +kubebuilder:validation:XValidation:rule="size(self.name) > 0",message="domainRef.name must not be empty"
	DomainRef refs.NamespacedName `json:"domainRef"`

	// DomainWhitelist Email domains allowed to authenticate through this identity provider. When set, users whose email domain is not listed are rejected.
	// +kubebuilder:validation:Optional
	DomainWhitelist []string `json:"domainWhitelist,omitempty"`

	// GroupMapper Group mapper: assigns AM groups based on provider attribute values. Each entry maps a group to the user attribute expressions that grant it.
	// +kubebuilder:validation:Optional
	GroupMapper map[string][]string `json:"groupMapper,omitempty"`

	// Mappers Attribute mappers: maps provider claims to AM user profile attributes.
	// +kubebuilder:validation:Optional
	Mappers map[string]string `json:"mappers,omitempty"`

	// Name Human-readable name of the identity provider.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=255
	Name *string `json:"name,omitempty"`

	// RoleMapper Role mapper: assigns AM roles based on provider attribute values. Each entry maps a role to the user attribute expressions that grant it.
	// +kubebuilder:validation:Optional
	RoleMapper map[string][]string `json:"roleMapper,omitempty"`

	// System Whether this is the domain's system identity provider. Immutable after creation. When true, only key is required; the identity provider is built from the domains.identities.default.* system settings and the name, type, and configuration fields are ignored.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	// +kubebuilder:default=false
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="system is immutable"
	System *bool `json:"system,omitempty"`

	// Type Identity provider plugin type identifier. Immutable after creation.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty"`
}
