// Package reporter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package reporter

import (
	"github.com/gravitee-io/gravitee-kubernetes-operator/api/model/refs"
	"github.com/gravitee-io/gravitee-kubernetes-operator/api/model/utils"
)

// AutomationReporter A reporter managed under a domain by the Automation API. Reporters persist audit events to a backend. The key field is the stable, immutable identity used for idempotent create-or-update.
// +kubebuilder:validation:XValidation:rule="(has(self.system) && self.system) || (has(self.name) && has(self.type) && has(self.configuration))",message="name, type and configuration are required unless system is true"
// +kubebuilder:validation:XValidation:rule="has(self.type) == has(oldSelf.type) && (!has(self.type) || self.type == oldSelf.type)",message="type is immutable"
type AutomationReporter = Reporter

// Reporter A reporter managed under a domain by the Automation API. Reporters persist audit events to a backend. The key field is the stable, immutable identity used for idempotent create-or-update.
// +kubebuilder:validation:XValidation:rule="(has(self.system) && self.system) || (has(self.name) && has(self.type) && has(self.configuration))",message="name, type and configuration are required unless system is true"
// +kubebuilder:validation:XValidation:rule="has(self.type) == has(oldSelf.type) && (!has(self.type) || self.type == oldSelf.type)",message="type is immutable"
type Reporter struct {
	// AttributeMappingEventTypes Audit event types the attribute mappings apply to. Empty means every event type. Ignored when system is true.
	// +kubebuilder:validation:Optional
	// +listType=set
	AttributeMappingEventTypes []string `json:"attributeMappingEventTypes,omitempty"`

	// AttributeMappings Additional attributes exported alongside the regular audit payload. Each entry pairs an expression read from the audit context with the field name its value is exported under. Ignored when system is true; a system reporter exports no additional attributes.
	// +kubebuilder:validation:Optional
	AttributeMappings []ReporterAttributeMapping `json:"attributeMappings,omitempty"`

	// Configuration Plugin-specific configuration, a free-form object sent to AM as a JSON string. Its shape is defined by the reporter type.
	// +kubebuilder:validation:Optional
	Configuration *utils.GenericStringMap `json:"configuration,omitempty"`

	// DomainRef Domain CRD reference
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="domainRef is immutable"
	// +kubebuilder:validation:XValidation:rule="size(self.name) > 0",message="domainRef.name must not be empty"
	DomainRef refs.NamespacedName `json:"domainRef"`

	// Enabled Whether the reporter is enabled.
	// +kubebuilder:validation:Optional
	// Defaults to true.
	// +kubebuilder:default=true
	Enabled *bool `json:"enabled,omitempty"`

	// Name Human-readable name of the reporter.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=255
	Name *string `json:"name,omitempty"`

	// System Whether this is the domain's system reporter. Immutable after creation. When true, only domainRef is required; the reporter is built from the domains.reporters.default.* system settings and the name, type, configuration, attributeMappings and attributeMappingEventTypes fields are ignored.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	// +kubebuilder:default=false
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="system is immutable"
	System *bool `json:"system,omitempty"`

	// Type Reporter plugin type identifier. Immutable after creation.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty"`
}

// ReporterAttributeMapping Exports one additional attribute, read from the audit context by expression, under a chosen field name.
type ReporterAttributeMapping struct {
	// ExportedName The name the evaluated value takes on the exported payload.
	// +kubebuilder:validation:Optional
	ExportedName *string `json:"exportedName,omitempty"`

	// Expression Expression evaluated against the audit context.
	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty"`
}
