//go:build !ignore_autogenerated

/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package reporter

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reporter) DeepCopyInto(out *Reporter) {
	*out = *in
	if in.AttributeMappingEventTypes != nil {
		in, out := &in.AttributeMappingEventTypes, &out.AttributeMappingEventTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AttributeMappings != nil {
		in, out := &in.AttributeMappings, &out.AttributeMappings
		*out = make([]ReporterAttributeMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = (*in).DeepCopy()
	}
	out.DomainRef = in.DomainRef
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.System != nil {
		in, out := &in.System, &out.System
		*out = new(bool)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reporter.
func (in *Reporter) DeepCopy() *Reporter {
	if in == nil {
		return nil
	}
	out := new(Reporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReporterAttributeMapping) DeepCopyInto(out *ReporterAttributeMapping) {
	*out = *in
	if in.ExportedName != nil {
		in, out := &in.ExportedName, &out.ExportedName
		*out = new(string)
		**out = **in
	}
	if in.Expression != nil {
		in, out := &in.Expression, &out.Expression
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReporterAttributeMapping.
func (in *ReporterAttributeMapping) DeepCopy() *ReporterAttributeMapping {
	if in == nil {
		return nil
	}
	out := new(ReporterAttributeMapping)
	in.DeepCopyInto(out)
	return out
}
