pull_request_rules:
    - name: Apply commits on `alpha`
      conditions:
          - label=apply-on-alpha
      actions:
          backport:
              branches:
                  - alpha
              assignees:
                  - "{{ author }}"
              body: |
                  This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

                  ----

                  {{ body }}

                  ----
                  {{ cherry_pick_error }}
              title: "[alpha] {{ title }}"
    - name: Apply commits on `beta`
      conditions:
          - label=apply-on-beta
      actions:
          backport:
              branches:
                  - beta
              assignees:
                  - "{{ author }}"
              body: |
                  This is an automatic copy of pull request #{{number}} done by [Mergify](https://mergify.com).

                  ----

                  {{ body }}

                  ----
                  {{ cherry_pick_error }}
              title: "[beta] {{ title }}"
