= Gravitee.io Kubernetes Operator

image:https://img.shields.io/badge/License-Apache%202.0-blue.svg["License", link="https://github.com/gravitee-io/gravitee-kubernetes-operator/blob/master/LICENSE.txt"]
image:https://circleci.com/gh/gravitee-io/gravitee-kubernetes-operator/tree/alpha.svg?style=svg[link="https://app.circleci.com/pipelines/github/gravitee-io/gravitee-kubernetes-operator?branch=alpha"]
image:https://goreportcard.com/badge/github.com/gravitee-io/gravitee-kubernetes-operator["Go Report Card", link="https://goreportcard.com/report/github.com/gravitee-io/gravitee-kubernetes-operator"]

image:./.assets/gravitee-logo-cyan.svg["Gravitee.io",400]

== Introduction

You can use the Gravitee Kubernetes Operator (GKO) to define, deploy, and publish APIs to your API Portal and API Gateway through Custom Resource Definitions (CRDs).

== User documentation

You can find detailed information about the Gravitee Kubernetes Operator in the following sections of the Gravitee user documentation:

  * link:https://documentation.gravitee.io/apim/guides/gravitee-kubernetes-operator[Overview^]
  * link:https://documentation.gravitee.io/apim/getting-started/install-and-upgrade-guides/install-on-kubernetes/architecture-overview[Architecture^]
  * link:https://documentation.gravitee.io/apim/guides/gravitee-kubernetes-operator/quick-start[Quick Start^]
  * link:https://documentation.gravitee.io/apim/guides/gravitee-kubernetes-operator/installation[Installation and deployment^]

The GKO API reference documentation is available https://github.com/gravitee-io/gravitee-kubernetes-operator/blob/master/docs/api/reference.md[here^].

== Developer guide

=== Initializing your environment

* Install link:https://www.docker.com/[Docker^]
* Install link:https://kubernetes.io/docs/tasks/tools/#kubectl[kubectl^]
* Install link:https://helm.sh/docs/intro/install/[Helm^]
* Install link:https://kind.sigs.k8s.io/docs/user/quick-start/#installation[kind^]
* Install link:https://nodejs.org/en/download/[NodeJs^]
* Install the operator-sdk: `brew install operator-sdk`

=== Installing tooling for development

All the tool needed to run the make targets used during development can be installed by running the following command:

[source,shell]
----
make install-tools
----

To get more information about the available make targets, run:

[source,shell]
----
make help
----

=== Running the operator locally

To run the operator locally against an APIM-ready local cluster, run the following commands:

[source,shell]
----
# Initialize a local kubernetes cluster running APIM
make start-cluster

# Install the operator CRDs into the cluster
make install

# Run the operator controller on your local machine
make run
----

=== Writing integration tests

Please refer to this link:https://github.com/gravitee-io/gravitee-kubernetes-operator/blob/master/test/integration/README.md[document^] for guidance, conventions and best practices regarding integration testing.

=== Debugging

To be able to run the operator against a local instance of both an APIM Gateway and an APIM Management API, you will need to:

* Attach to a local cluster context.
* Create a local service account to authenticate the gateway against the local cluster.
* Create a Management Context pointing to your local APIM Management API.
* Run what you need to debug in debug mode.

[source,shell]
----
# Create a service account token with 'cluster-admin' role in the current context and
# use this token to authenticate against the current cluster
make cluster-admin

make run # or run using a debugger if you need to debug the operator as well
----

If you are using visual studio code, here is a working config snippet for debugging the operator:

[source,json]
----
{
    "name": "Main",
    "type": "go",
    "request": "launch",
    "mode": "auto",
    "program": "main.go",
    "env": {
        "DEV_MODE": "true",
        "NAMESPACE": "",
    },
}
----

And here is another snippet for debugging integration test execution

[source,json]
----
{
  "name": "Test API Definition",
  "type": "go",
  "request": "launch",
  "mode": "auto",
  "program": "test/integration/apidefinition/suite_test.go"
}
----

=== Working with the repo

If you are submitting a change to the operator code please make sure that your code is covered by an link:https://github.com/gravitee-io/gravitee-kubernetes-operator/blob/master/test/integration/README.md[integration test^]

If you are submitting a change to the helm charts, please make sure that it is covered by a link:https://github.com/gravitee-io/gravitee-kubernetes-operator/tree/master/helm/gko/tests[helm unit test^]

Before committing your changes don't forget to run the following make targets

[source,shell]
----
# If you commit a change to the operator model
make generate manifests reference 
# If you commit a change to the helm chart values
make helm-reference 
# In any case
make lint-fix
----

When committing your contributions, please follow the link:https://www.conventionalcommits.org/en/v1.0.0/[conventional commits^] convention.

