#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: Secret
metadata:
  name: ca-cert-secret
type: Opaque
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC/TCCAeWgAwIBAgIUA7jzcEPvNmoTfL08AgcRbcdt3KMwDQYJKoZIhvcNAQEL
    BQAwDjEMMAoGA1UEAwwDR0tPMB4XDTI2MDIyMDA5MDE1MVoXDTM2MDIxODA5MDE1
    MVowDjEMMAoGA1UEAwwDR0tPMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEAsZVXVYEvQMPUoT/rwpZd8cUPJnHG9cz5DL1lUdPG4qeaGZvChy3yYFdSPFck
    aDp7tUoHQn2xM+xO/hM9+A2U31R2OCgRUSmYJ9IUfa/w4D/MGSQmsQ72kSqrG+xs
    UjgHWzwVrVYsK/r19oargQSXdsOASuPJmVQW/lQttYV/ov/jyiJGMipyeBikjagU
    q+WDggr9GUuE7BW5Zn6/KC4HsW2ooHDRe97QAIYd2SYD4+tFRDTrEuBbWWDi3aDy
    IFstZAPfkrHy+HxpLb7onkulTsZBRk6LRRxxEsfVyWaf1zGH32Nu0466vXZDwVth
    0zSkB9EZQw7dudnzKq6Neng30QIDAQABo1MwUTAdBgNVHQ4EFgQU2QW3/tRlkMxV
    nnmVw0NUMJHmu+gwHwYDVR0jBBgwFoAU2QW3/tRlkMxVnnmVw0NUMJHmu+gwDwYD
    VR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEActb3saoogY8HUk7lxlEt
    mNPMNkFb79SRC43oZNYBw4et/v3Jek7EqDEZlUGq/SmZqK86KoMzL+F9LGfNYB0j
    1VJ3mc4rTi3FIOSdhyFzDiu4X3FE8J6YYhDaV01jgl2gF2jQSrvGtMalk6NkiBkT
    uckPRb57qaEnND1WdVMDGiOMecmf9XwNla4KScHkiMh3/8sP78DtWHUuF6tk+F9E
    d8NlqIMLTZjd9OfIl9uDSU3Bom6dTPGyNbuIRJpctdivzagl2rZ+88QDfB2nPJDr
    aOfB+BbcapxPek/uPpL9e9cfbrV7qT6KQNrGmwDfWBMnegppRXaetzPHAQfhsCoL
    KQ==
    -----END CERTIFICATE-----
