# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- if and .Values.manager.metrics.enabled .Values.manager.metrics.prometheus.monitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    release: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "helm.name" . }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ template "helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: gko-metrics-monitor
spec:
  endpoints:
    - path: /metrics
      {{- if .Values.manager.metrics.secured }}
      port: https
      scheme: https
      {{- else }}
      port: http
      scheme: http
      {{- end }}
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify:  {{ .Values.manager.metrics.prometheus.monitor.insecureSkipCertVerify }}
  selector:
    matchLabels:
      control-plane: controller-manager
{{- end }}
