# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.rbac.create }}
{{- if not .Values.rbac.skipClusterRoles }}
{{- if .Values.manager.scope.cluster }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "rbac.ClusterRoleName" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "helm.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - gravitee.io
    resources:
      - apidefinitions
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - gravitee.io
    resources:
      - apidefinitions/finalizers
    verbs:
      - update
  - apiGroups:
      - gravitee.io
    resources:
      - apidefinitions/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - gravitee.io
    resources:
      - apiv4definitions
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - gravitee.io
    resources:
      - apiv4definitions/finalizers
    verbs:
      - update
  - apiGroups:
      - gravitee.io
    resources:
      - apiv4definitions/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - gravitee.io
    resources:
      - apiresources
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - gravitee.io
    resources:
      - apiresources/finalizers
    verbs:
      - update
  - apiGroups:
      - gravitee.io
    resources:
      - apiresources/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - gravitee.io
    resources:
      - managementcontexts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - gravitee.io
    resources:
      - managementcontexts/finalizers
    verbs:
      - update
  - apiGroups:
      - gravitee.io
    resources:
      - managementcontexts/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - gravitee.io
    resources:
      - applications
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - gravitee.io
    resources:
      - applications/finalizers
    verbs:
      - update
  - apiGroups:
      - gravitee.io
    resources:
      - applications/status
    verbs:
      - get
      - patch
      - update
{{- end }}
{{- end }}
{{- end }}
