# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.rbac.create }}
# if not clusterScope or if clusterScope but with Namespaces
{{- if or (not .Values.manager.scope.cluster) (and .Values.manager.scope.cluster .Values.manager.scope.namespaces) }}
{{- $name := include "helm.name" . -}}
{{- $roleName := include "rbac.RoleName" . -}}
{{- $clusterRoleName := include "rbac.ClusterRoleName" . -}}
{{- $serviceAccountName := include "rbac.serviceAccountName" . -}}
{{- $namespaces := include "manager.Namespaces" . -}}
{{range $i, $namespace := splitList "," $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-binding" $roleName }}
  {{ if (eq $namespaces "\"\"") }}
  namespace: {{ $.Release.Namespace }}
  {{ else }}
  namespace: {{ $namespace }}
  {{ end }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
  annotations:
    meta.helm.sh/release-name: {{ $.Release.Name }}
    meta.helm.sh/release-namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if or ($.Values.manager.scope.cluster) (gt (len $.Values.manager.scope.namespaces) 1) }}
  kind: ClusterRole
  name: {{ $clusterRoleName }}
  {{ else }}
  kind: Role
  name: {{ $roleName }}
  {{ end }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: '{{ $.Release.Namespace }}'
{{- end }}
{{- end }}
{{- end }}

