/**
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Xray test ID registry.
 *
 * Use these constants in test titles for filtering with --grep:
 *   test(`should start API ${XRAY.API_LIFECYCLE.START_STOP}`, ...)
 *
 * Run a single Xray test:
 *   npm run e2e -- --grep @GKO-1464
 *
 * Run regression pack:
 *   npm run e2e:regression
 */

export const XRAY = {
  API_LIFECYCLE: {
    DEPLOY_V4_SYNC_K8S: "@GKO-69",
    DEPLOY_V4_SYNC_FROM_MGMT: "@GKO-71",
    DEPLOY_V4_WITH_LABELS_CATEGORIES: "@GKO-83",
    STOP_V4_API: "@GKO-124",
    START_STOPPED_V4_API: "@GKO-126",
    DELETE_V4_API: "@GKO-140",
    UPDATE_V4_MESSAGE_API: "@GKO-141",
    UPDATE_V4_MESSAGE_MISSING_FIELDS: "@GKO-142",
    MISSING_REQUIRED_FIELDS_V4_PROXY: "@GKO-165",
    NO_DEPLOY_WHEN_NO_CHANGES: "@GKO-176",
    REDEPLOY_AFTER_DELETE: "@GKO-212",
    CONTEXT_PATH_CONFLICT_V4: "@GKO-469",
    NO_PLANS_STARTED_V4: "@GKO-502",
    NO_PLANS_STOPPED_V4: "@GKO-503",
    FAILOVER_V4_PROXY: "@GKO-859",
    START_STOP_V2_V4_NATIVE: "@GKO-1464",
  },
  PLANS: {
    KEYLESS_PLAN_V4: "@GKO-110",
    DELETE_PLAN_SYNC_MGMT: "@GKO-113",
    DELETE_PLAN_SYNC_K8S: "@GKO-117",
    MULTIPLE_PLANS: "@GKO-160",
    APIKEY_PLAN_V4: "@GKO-161",
    PUBLISHED_PLAN: "@GKO-169",
    FAIL_NON_PUBLISHED_STATUS: "@GKO-170",
    FAIL_CHANGE_PUBLISHED_STATUS: "@GKO-171",
    PLAN_PUBLISHED_WHEN_API_STOPPED: "@GKO-174",
    NATIVE_KAFKA_KEYLESS_PLAN: "@GKO-856",
    NATIVE_ADD_PLAN: "@GKO-918",
    NATIVE_REMOVE_PLAN: "@GKO-919",
    NATIVE_UPDATE_PLAN: "@GKO-920",
    NATIVE_MULTIPLE_PLANS: "@GKO-921",
    NATIVE_NO_PLAN: "@GKO-922",
  },
  WEBHOOKS: {
    REJECT_INVALID_CRS: "@GKO-1447",
    NON_OAS_COMPLIANT_V4: "@GKO-76",
    INVALID_CREDENTIALS_CONTEXT: "@GKO-78",
    MISSING_FIELDS_V4_MESSAGE: "@GKO-166",
    NON_EXISTING_CONTEXT_V4: "@GKO-414",
    NON_EXISTING_MGMT_CONTEXT: "@GKO-465",
    MGMT_CONTEXT_INVALID_CREDS: "@GKO-474",
    RESOURCE_NO_NAME: "@GKO-515",
    RESOURCE_NO_TYPE: "@GKO-516",
    RESOURCE_NO_CONFIG: "@GKO-518",
    RESOURCE_INVALID_CONFIG: "@GKO-519",
  },
  APPLICATIONS: {
    APP_WITH_METADATA: "@GKO-194",
    CREATE_APP: "@GKO-335",
    UPDATE_APP: "@GKO-336",
    DELETE_APP: "@GKO-337",
    APP_NO_MGMT_CONTEXT: "@GKO-526",
    APP_NEW_CRD_ATTRIBUTES: "@GKO-527",
    APP_BOTH_SETTINGS_ERROR: "@GKO-550",
    APP_CONFIGURE_SETTINGS: "@GKO-552",
    APP_PO_IN_MEMBERS_ERROR: "@GKO-558",
    APP_SWITCH_SETTINGS_TYPE: "@GKO-561",
    APP_UPDATE_OAUTH_TYPE: "@GKO-562",
    APP_CLIENT_ID_OPTIONAL: "@GKO-563",
    APP_CLIENT_ID_UNIQUE: "@GKO-564",
    APP_PO_ROLE_OVERWRITE: "@GKO-567",
  },
  SUBSCRIPTIONS: {
    ENDING_BEFORE_START: "@GKO-807",
    SYNC_FROM_K8S_ERROR_V4: "@GKO-816",
    API_MUST_BE_STARTED: "@GKO-840",
    PLAN_MUST_MATCH_V2: "@GKO-842",
    PLAN_MUST_MATCH_V4: "@GKO-843",
    SECURITY_TYPE_JWT_OAUTH2: "@GKO-844",
    API_KIND_DEFAULT: "@GKO-845",
    ERROR_UPDATE_PLAN_WITH_SUB: "@GKO-848",
    ERROR_DELETE_API_WITH_SUB: "@GKO-849",
    ERROR_DELETE_APP_WITH_SUB: "@GKO-853",
  },
  NATIVE_APIS: {
    NON_NATIVE_PLAN_ERROR: "@GKO-874",
    NON_NATIVE_FLOW_ERROR: "@GKO-875",
  },
  DEPLOYMENT_RECONCILIATION: {
    RECONCILE_API_CONFIG: "@GKO-1444",
    ACCEPTED_FALSE_ON_FAILURE: "@GKO-1387",
    ACCEPTED_NOT_FALSE_ON_SUCCESS: "@GKO-1388",
    ACCEPTED_UPDATES_ON_CHANGE: "@GKO-1389",
    PROCESSING_STATUS_PRESENT: "@GKO-1390",
    RESOLVED_REFS_NOT_PRESENT: "@GKO-1392",
    IDEMPOTENT_RECONCILIATION: "@GKO-1445",
    STATUS_CONDITIONS_REFLECT_STATE: "@GKO-1446",
  },
  MANAGEMENT_CONTEXT: {
    NON_EXISTING_ENV: "@GKO-472",
    NON_EXISTING_ORG: "@GKO-473",
    INVALID_CREDENTIALS: "@GKO-474",
    DELETE_WITH_V2_API_REF: "@GKO-892",
    DELETE_WITH_V4_API_REF: "@GKO-893",
    DELETE_WITH_APP_REF: "@GKO-894",
    DELETE_NO_REFS: "@GKO-895",
  },
  POLICIES: {
    DEPLOY_V4_WITH_POLICY: "@GKO-94",
    REMOVE_POLICY: "@GKO-95",
    UPDATE_POLICY: "@GKO-96",
  },
  CATEGORIES: {
    VALID_CATEGORY_V4: "@GKO-267",
    NON_EXISTING_CATEGORY_V4: "@GKO-269",
    REMOVE_CATEGORY_V4: "@GKO-270",
  },
  TERRAFORM: {
    APPLY_COMPLEX_CONFIG: "@GKO-1926",
    APIM_CONTAINS_ALL_ENTITIES: "@GKO-1929",
    PAGE_HIERARCHY_PRESERVED: "@GKO-1931",
    IDEMPOTENT_CONFIG: "@GKO-1932",
    ADD_APPLICATION: "@GKO-1373",
    ADD_SUBSCRIPTION: "@GKO-1374",
    APP_MISSING_FIELDS: "@GKO-1375",
    INVALID_SUBSCRIPTION_FORMAT: "@GKO-1376",
    REMOVE_APPLICATION: "@GKO-1378",
    CREATE_APP_AND_SUBSCRIPTION: "@GKO-1379",
    VALID_AND_MALFORMED_HCL: "@GKO-1453",
  },
} as const;

export const TAGS = {
  REGRESSION: "@regression",
} as const;
