apiVersion: gravitee.io/v1alpha1
kind: ApiResource
metadata:
  name: reusable-resource-keycloak-adapter
  namespace: default
spec:
  name: "keycloak-adapter"
  type: "oauth2-keycloak-resource"
  enabled: true
  configuration:
      validateTokenLocally: true
      userClaim: "sub"
      verifyHost: false
      trustAll: true
      keycloakConfiguration:
          "{\n                \"realm\": \"gravitee\",\n      \
          \          \"auth-server-url\": \"http://localhost:8080/auth\",\n        \
          \        \"ssl-required\": \"external\",\n                \"resource\": \"\
          gravitee\",\n                \"credentials\": {\n                    \"secret\"\
          : \"f1c9ff64-abcf-4671-9ddb-4fe4a172390d\"\n                },\n         \
          \       \"confidential-port\": 0,\n                \"policy-enforcer\": {}\n\
          }"
