apiVersion: gravitee.io/v1alpha1
kind: ApiResource
metadata:
  name: reusable-resource-ldap-auth-provider
spec:
  name: "ldap-auth"
  type: "auth-provider-ldap-resource"
  enabled: true
  configuration:
      contextSourceUrl: "ldap://localhost:1389"
      userSearchFilter: "uid={0}"
      userSearchBase: "ou=users"
      cacheMaxElements: 100
      cacheTimeToLive: 60000
      connectTimeout: 5000
      responseTimeout: 5000
      minPoolSize: 1
      maxPoolSize: 1
      contextSourceBase: "dc=example,dc=com"
      contextSourceUsername: "cn=Directory Manager"
      contextSourcePassword: "password"
