---
apiVersion: "gravitee.io/v1alpha1"
kind: "ApiDefinition"
metadata:
    name: "with-am-oauth2-resource"
    namespace: default
spec:
    name: "with-am-oauth2-resource"
    version: "1"
    description: "With AM Oauth2 Resource"
    visibility: "PRIVATE"
    flows: []
    gravitee: "2.0.0"
    flow_mode: "DEFAULT"
    resources:
        - name: "oauth2-am-resource"
          type: "oauth2-am-resource"
          enabled: true
          configuration:
              useSystemProxy: false
              version: "V3_X"
              userClaim: "sub"
              serverURL: "https://authorization-server.com/authorize"
              securityDomain: "gravitee"
              clientId: "0roMt9mBy1Fm_78suKoTdpIh"
              clientSecret: "0roMt9mBy1Fm_78suKoTdpIh"
    properties: []
    plans:
        - name: "free"
          description: "Free Plan"
          validation: "AUTO"
          security: "KEY_LESS"
          type: "API"
          status: "PUBLISHED"
          order: 0
          characteristics: []
          paths: {}
          flows:
              - name: ""
                path-operator:
                    path: "/"
                    operator: "STARTS_WITH"
                condition: ""
                consumers: []
                methods: []
                pre: []
                post: []
                enabled: true
          comment_required: false
        - name: "Oauth2"
          description: "Oauth2 AM Plan"
          validation: "MANUAL"
          security: "OAUTH2"
          securityDefinition:
              "{\"extractPayload\":false,\"checkRequiredScopes\":false,\"\
              modeStrict\":true,\"propagateAuthHeader\":true,\"oauthResource\":\"oauth2-am-resource\"\
              }"
          type: "API"
          status: "STAGING"
          order: 0
          characteristics: []
          paths: {}
          flows:
              - name: ""
                path-operator:
                    path: "/"
                    operator: "STARTS_WITH"
                condition: ""
                consumers: []
                methods: []
                pre: []
                post: []
                enabled: true
          comment_required: false
    path_mappings: []
    proxy:
        virtual_hosts:
            - path: "/with-am-oauth2/"
        strip_context_path: false
        preserve_host: false
        groups:
            - name: "default-group"
              endpoints:
                  - backup: false
                    inherit: true
                    name: "default"
                    weight: 1
                    type: "http"
                    target: "https://api.gravitee.io/echo"
              load_balancing:
                  type: "ROUND_ROBIN"
              http:
                  connectTimeout: 5000
                  idleTimeout: 60000
                  keepAlive: true
                  readTimeout: 10000
                  pipelining: false
                  maxConcurrentConnections: 100
                  useCompression: true
                  followRedirects: false
    response_templates: {}


