---
apiVersion: "gravitee.io/v1alpha1"
kind: "ApiDefinition"
metadata:
    name: "with-cache-resource"
    namespace: default
spec:
    name: "with-cache"
    version: "1"
    description: "With Cache Resource"
    visibility: "PRIVATE"
    flows: []
    gravitee: "2.0.0"
    flow_mode: "DEFAULT"
    resources:
        - name: "cache-resource"
          type: "cache"
          enabled: true
          configuration:
              timeToIdleSeconds: 0
              timeToLiveSeconds: 0
              maxEntriesLocalHeap: 1000
    properties: []
    plans:
        - name: "free"
          description: "Free Plan"
          validation: "AUTO"
          security: "KEY_LESS"
          type: "API"
          status: "PUBLISHED"
          order: 0
          characteristics: []
          paths: {}
          flows:
              - name: ""
                path-operator:
                    path: "/"
                    operator: "STARTS_WITH"
                condition: ""
                consumers: []
                methods: []
                pre:
                    - name: "Cache"
                      description: "Cache policy"
                      enabled: true
                      policy: "cache"
                      configuration:
                          timeToLiveSeconds: 600
                          cacheName: "cache-resource"
                          methods:
                              - "GET"
                              - "OPTIONS"
                              - "HEAD"
                          scope: "APPLICATION"
                          key: "cache-key"
                post: []
                enabled: true
          comment_required: false
    path_mappings: []
    proxy:
        virtual_hosts:
            - path: "/with-cache/"
        strip_context_path: false
        preserve_host: false
        groups:
            - name: "default-group"
              endpoints:
                  - backup: false
                    inherit: true
                    name: "default"
                    weight: 1
                    type: "http"
                    target: "https://api.gravitee.io/echo"
              load_balancing:
                  type: "ROUND_ROBIN"
              http:
                  connectTimeout: 5000
                  idleTimeout: 60000
                  keepAlive: true
                  readTimeout: 10000
                  pipelining: false
                  maxConcurrentConnections: 100
                  useCompression: true
                  followRedirects: false
    response_templates: {}
    contextRef:
        name: "dev-mgmt-ctx"
        namespace: "default"
