apiVersion: gravitee.io/v1alpha1
kind: ApiResource
metadata:
  name: reusable-resource-http-auth-provider
  namespace: default
spec:
  name: "http-auth"
  type: "auth-provider-http-resource"
  enabled: true
  configuration:
      method: "GET"
      condition: "{#authResponse.status == 200}"
      url: "http://httpbin.org/basic-auth/admin/admin"
      headers:
      - name: "Authorization"
        value: "Basic YWRtaW46YWRtaW4="
