---
apiVersion: "gravitee.io/v1alpha1"
kind: "ApiDefinition"
metadata:
    name: "with-generic-oauth2-resource"
    namespace: default
spec:
    name: "with-generic-oauth2-resource"
    version: "1"
    description: "With Generic OAUTH2 resource"
    visibility: "PRIVATE"
    flows: []
    gravitee: "2.0.0"
    flow_mode: "DEFAULT"
    resources:
        - name: "oauth2-generic-resource"
          type: "oauth2"
          enabled: true
          configuration:
              authorizationServerUrl: "https://authorization-server.com/authorize"
              introspectionEndpoint: "https://authorization-server.com/token"
              useSystemProxy: false
              introspectionEndpointMethod: "GET"
              userInfoEndpoint: "/userinfo"
              userInfoEndpointMethod: "GET"
              useClientAuthorizationHeader: true
              clientAuthorizationHeaderName: "Authorization"
              clientAuthorizationHeaderScheme: "Basic"
              tokenIsSuppliedByQueryParam: true
              tokenQueryParamName: "token"
              tokenIsSuppliedByHttpHeader: false
              tokenIsSuppliedByFormUrlEncoded: false
              tokenFormUrlEncodedName: "token"
              userClaim: "sub"
              clientId: "0roMt9mBy1Fm_78suKoTdpIh"
              scopeSeparator: " ,"
              clientSecret: "YcNbtCHtOvvznmFhjCCbl6u-wp827MElS3m7l1Hsoupw4M4f"
    properties: []
    plans:
        - name: "oauth2"
          description: "OAUTH2 Plan"
          validation: "AUTO"
          security: "OAUTH2"
          securityDefinition:
              "{\"extractPayload\":false,\"checkRequiredScopes\":false,\"\
              modeStrict\":true,\"propagateAuthHeader\":true,\"oauthResource\":\"oauth2-generic-resource\"\
              }"
          type: "API"
          status: "STAGING"
          order: 0
          characteristics: []
          paths: {}
          flows:
              - name: ""
                path-operator:
                    path: "/"
                    operator: "STARTS_WITH"
                condition: ""
                consumers: []
                methods: []
                pre: []
                post: []
                enabled: true
          comment_required: false
        - name: "free"
          description: "Free Plan"
          validation: "AUTO"
          security: "KEY_LESS"
          type: "API"
          status: "PUBLISHED"
          order: 0
          characteristics: []
          paths: {}
          flows:
              - name: ""
                path-operator:
                    path: "/"
                    operator: "STARTS_WITH"
                condition: ""
                consumers: []
                methods: []
                pre: []
                post: []
                enabled: true
          comment_required: false
    path_mappings: []
    proxy:
        virtual_hosts:
            - path: "/with-generic-oauth2/"
        strip_context_path: false
        preserve_host: false
        groups:
            - name: "default-group"
              endpoints:
                  - backup: false
                    inherit: true
                    name: "default"
                    weight: 1
                    type: "http"
                    target: "https://api.gravitee.io/echo"
              load_balancing:
                  type: "ROUND_ROBIN"
              http:
                  connectTimeout: 5000
                  idleTimeout: 60000
                  keepAlive: true
                  readTimeout: 10000
                  pipelining: false
                  maxConcurrentConnections: 100
                  useCompression: true
                  followRedirects: false
    response_templates: {}
    local: true
