---
apiVersion: "gravitee.io/v1alpha1"
kind: "ApiDefinition"
metadata:
    name: "with-cache-redis-resource"
  
spec:
    name: "with-cache-redis-resource"
    version: "1"
    description: "With Cache Redis"
    visibility: "PRIVATE"
    flows: []
    gravitee: "2.0.0"
    flow_mode: "DEFAULT"
    resources:
        - name: "redis-cache"
          type: "cache-redis"
          enabled: true
          configuration:
              releaseCache: false
              maxTotal: 8
              timeToLiveSeconds: 0
              timeout: 2000
              useSsl: true
              standalone:
                  enabled: true
                  host: "localhost"
                  port: 6379
              sentinel:
                  enabled: false
                  masterId: "sentinel-master"
              password: "redispassword"
    properties: []
    plans:
        - name: "free"
          description: "Free Plan"
          validation: "AUTO"
          security: "KEY_LESS"
          type: "API"
          status: "PUBLISHED"
          order: 0
          characteristics: []
          paths: {}
          flows:
              - name: ""
                path-operator:
                    path: "/"
                    operator: "STARTS_WITH"
                condition: ""
                consumers: []
                methods: []
                pre:
                    - name: "Cache"
                      description: "cache-redis"
                      enabled: true
                      policy: "cache"
                      configuration:
                          timeToLiveSeconds: 600
                          cacheName: "redis-cache"
                          methods:
                              - "GET"
                              - "OPTIONS"
                              - "HEAD"
                          useResponseCacheHeaders: true
                          scope: "APPLICATION"
                post: []
                enabled: true
          comment_required: false
    path_mappings: []
    proxy:
        virtual_hosts:
            - path: "/with-cache-redis/"
        strip_context_path: false
        preserve_host: false
        groups:
            - name: "default-group"
              endpoints:
                  - backup: false
                    inherit: true
                    name: "default"
                    weight: 1
                    type: "http"
                    target: "https://api.gravitee.io/echo"
              load_balancing:
                  type: "ROUND_ROBIN"
              http:
                  connectTimeout: 5000
                  idleTimeout: 60000
                  keepAlive: true
                  readTimeout: 10000
                  pipelining: false
                  maxConcurrentConnections: 100
                  useCompression: true
                  followRedirects: false
    response_templates: {}
    local: true
