---
apiVersion: "gravitee.io/v1alpha1"
kind: "ApiDefinition"
metadata:
    name: "with-inline-auth-provider"
    namespace: default
spec:
    name: "with-inline-auth-provider"
    version: "1"
    description: "With Inline Auth Provider"
    visibility: "PRIVATE"
    flows: []
    gravitee: "2.0.0"
    flow_mode: "DEFAULT"
    resources:
        - name: "inline-auth"
          type: "auth-provider-inline-resource"
          enabled: true
          configuration:
              users:
                  - username: "user"
                    password: "password"
    properties: []
    plans:
        - name: "free"
          description: "Free Plan"
          validation: "AUTO"
          security: "KEY_LESS"
          type: "API"
          status: "PUBLISHED"
          order: 0
          characteristics: []
          paths: {}
          flows:
              - name: ""
                path-operator:
                    path: "/"
                    operator: "STARTS_WITH"
                condition: ""
                consumers: []
                methods: []
                pre:
                    - name: "Basic Authentication"
                      description: ""
                      enabled: true
                      policy: "policy-basic-authentication"
                      configuration:
                          authenticationProviders:
                              - "inline-auth"
                          realm: "gravitee.io"
                post: []
                enabled: true
          comment_required: false
    path_mappings: []
    proxy:
        virtual_hosts:
            - path: "/with-inline-auth/"
        strip_context_path: false
        preserve_host: false
        groups:
            - name: "default-group"
              endpoints:
                  - backup: false
                    inherit: true
                    name: "default"
                    weight: 1
                    type: "http"
                    target: "https://api.gravitee.io/echo"
              load_balancing:
                  type: "ROUND_ROBIN"
              http:
                  connectTimeout: 5000
                  idleTimeout: 60000
                  keepAlive: true
                  readTimeout: 10000
                  pipelining: false
                  maxConcurrentConnections: 100
                  useCompression: true
                  followRedirects: false
    response_templates: {}


