apiVersion: gravitee.io/v1alpha1
kind: ApiResource
metadata:
  name: reusable-resource-cache-redis
spec:
  name: "redis-cache"
  type: "cache-redis"
  enabled: true
  configuration:
      releaseCache: false
      maxTotal: 8
      timeToLiveSeconds: 0
      timeout: 2000
      useSsl: true
      standalone:
          enabled: true
          host: "localhost"
          port: 6379
      sentinel:
          enabled: false
          masterId: "sentinel-master"
      password: "redispassword"
  local: true
