#
# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: gravitee.io/v1alpha1
kind: ApiDefinition
metadata:
  name: complex-api-example
spec:
  name: 0. Ì†æÌ∫ê Planets
  crossId: 778fba35-bdf6-4beb-8fba-35bdf68beb6a
  version: '1'
  description: The whole graviverse in your hands!
  visibility: PUBLIC
  gravitee: 2.0.0
  flow_mode: DEFAULT
  flows:
  - name: ''
    path-operator:
      path: "/"
      operator: STARTS_WITH
    condition: ''
    consumers: []
    methods: []
    pre:
    - name: Transform Headers
      description: ''
      enabled: true
      policy: transform-headers
      configuration:
        addHeaders:
        - name: x-demo-header
          value: new-value
        scope: REQUEST
    - name: Assign content
      description: ''
      enabled: false
      policy: policy-assign-content
      condition: '{#request.heraders["application"][0] == "1"}'
      configuration:
        scope: REQUEST
        body: '{ "key": "value" }'
    - name: Assign content
      description: ''
      enabled: false
      policy: policy-assign-content
      configuration:
        scope: REQUEST
        body: '{ "key": "A second value that should be displayed"}'
    - name: Api Key
      description: sss
      enabled: true
      policy: api-key
      configuration: {}
    post:
    - name: JSON to XML
      description: ''
      enabled: true
      policy: json-xml
      configuration:
        rootElement: root
        scope: RESPONSE
    enabled: true
  - name: ''
    path-operator:
      path: "/dby"
      operator: STARTS_WITH
    condition: ''
    consumers: []
    methods: []
    pre:
    - name: HTTP Callout
      description: ''
      enabled: true
      policy: policy-http-callout
      configuration:
        variables:
        - name: result
          value: "{#calloutResponse.content}"
        method: GET
        fireAndForget: false
        scope: REQUEST
        errorStatusCode: '500'
        errorCondition: "{#calloutResponse.status >= 400 and #calloutResponse.status
          <= 599}"
        url: https://api.gravitee.io/echo
        exitOnError: false
    - name: Mock
      description: ''
      enabled: true
      policy: mock
      configuration:
        content: "{#context.attributes[‚Äòresult‚Äô]}"
        status: '200'
    post: []
    enabled: true
  resources: []
  properties:
  - key: test
    value: toto
    encrypted: false
  labels:
  - uranus
  - venus
  - saturne
  - mars
  - terre
  - neptune
  - jupiter
  - mercure
  - pluton
  plans:
  - id: 58e3f814-0150-428a-a3f8-140150c28af6
    crossId: 753f065f-2eb6-426d-bf06-5f2eb6326d8e
    name: API Key
    description: Api key needed!
    validation: AUTO
    security: API_KEY
    securityDefinition: '{"propagateApiKey":true}'
    type: API
    status: PUBLISHED
    api: 8be358c9-be95-4b18-a358-c9be95bb1847
    order: 1
    characteristics: []
    paths: {}
    flows: []
    comment_required: false
  - id: 833a2790-5445-44ba-ba27-90544554ba72
    crossId: 81053edc-1524-49be-853e-dc152419be8d
    name: Keyless
    description: No money needed!
    validation: AUTO
    security: KEY_LESS
    securityDefinition: "{}"
    type: API
    status: PUBLISHED
    api: 8be358c9-be95-4b18-a358-c9be95bb1847
    order: 0
    characteristics: []
    paths:
      "/": []
    flows: []
    comment_required: false
  metadata:
  - key: email-support
    name: email-support
    format: MAIL
    value: "${(api.primaryOwner.email)!''}"
    defaultValue: support@change.me
  id: 8be358c9-be95-4b18-a358-c9be95bb1847
  path_mappings:
  - "/products/:id"
  proxy:
    virtual_hosts:
    - path: "/planets"
    - host: yann
      path: "/planets"
    strip_context_path: false
    preserve_host: false
    groups:
    - name: default-group
      endpoints:
      - backup: false
        inherit: true
        name: default
        weight: 1
        type: http
        target: https://api.le-systeme-solaire.net/rest/
      - backup: false
        inherit: true
        name: kafka
        weight: 1
        type: kafka
        target: kafka
      load_balancing:
        type: ROUND_ROBIN
      http:
        connectTimeout: 5000
        idleTimeout: 60000
        keepAlive: true
        readTimeout: 10000
        pipelining: false
        maxConcurrentConnections: 100
        useCompression: true
        followRedirects: false
  response_templates: {}
  primaryOwner:
    id: 4015f9f2-c0a4-4c0c-95f9-f2c0a4fc0c4c
    email: no-reply@graviteesource.com
    displayName: Admin master
    type: USER