# permissions for end users to view apidefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apidefinition-viewer-role
rules:
- apiGroups:
  - gravitee.io
  resources:
  - apidefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gravitee.io
  resources:
  - apidefinitions/status
  verbs:
  - get
