# permissions for end users to edit apidefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apidefinition-editor-role
rules:
- apiGroups:
  - gravitee.io
  resources:
  - apidefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gravitee.io
  resources:
  - apidefinitions/status
  verbs:
  - get
