# permissions for end users to edit apiresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiresource-editor-role
rules:
- apiGroups:
  - gravitee.io
  resources:
  - apiresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gravitee.io
  resources:
  - apiresources/status
  verbs:
  - get
