# permissions for end users to view managementcontexts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managementcontext-viewer-role
rules:
- apiGroups:
  - gravitee.io
  resources:
  - managementcontexts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gravitee.io
  resources:
  - managementcontexts/status
  verbs:
  - get
