---
apiVersion: rbac.authorization.k8s.io/v1
kind: '{{ ternary "ClusterRole" "Role" .Values.manager.scope.cluster }}'
metadata:
  creationTimestamp: null
  name: "manager-role-{{ .Release.Name }}-{{ .Release.Namespace }}"
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
