---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "manager-role-crd-{{ .Release.Name }}-{{ .Release.Namespace }}"
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - gravitee.io
  resources:
  - apidefinitions
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gravitee.io
  resources:
  - apidefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - gravitee.io
  resources:
  - apidefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gravitee.io
  resources:
  - apiresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gravitee.io
  resources:
  - apiresources/finalizers
  verbs:
  - update
- apiGroups:
  - gravitee.io
  resources:
  - apiresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gravitee.io
  resources:
  - managementcontexts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gravitee.io
  resources:
  - managementcontexts/finalizers
  verbs:
  - update
- apiGroups:
  - gravitee.io
  resources:
  - managementcontexts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
