// Package domain provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package domain

// AutomationAccountSettings User account settings for the domain: brute-force protection, registration, password reset, remember-me, and MFA challenge behavior.
type AutomationAccountSettings = AccountSettings

// AccountSettings User account settings for the domain: brute-force protection, registration, password reset, remember-me, and MFA challenge behavior.
type AccountSettings struct {
	// AccountBlockedDuration Duration, in seconds, for which the account remains blocked after too many failed login attempts.
	// +kubebuilder:validation:Optional
	AccountBlockedDuration *int32 `json:"accountBlockedDuration,omitempty"`

	// AutoLoginAfterRegistration Whether the user is automatically logged in after completing registration.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	AutoLoginAfterRegistration *bool `json:"autoLoginAfterRegistration,omitempty"`

	// AutoLoginAfterResetPassword Whether the user is automatically logged in after a password reset.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	AutoLoginAfterResetPassword *bool `json:"autoLoginAfterResetPassword,omitempty"`

	// CompleteRegistrationWhenResetPassword Whether resetting a password also completes a pending registration.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	CompleteRegistrationWhenResetPassword *bool `json:"completeRegistrationWhenResetPassword,omitempty"`

	// DefaultIdentityProviderForRegistration Key of an identity provider that exists under this domain, used as the default for user registration. Resolved against the domain's identity providers when applied; a value that does not match an existing identity provider is rejected with a 400 response.
	// +kubebuilder:validation:Optional
	DefaultIdentityProviderForRegistration *string `json:"defaultIdentityProviderForRegistration,omitempty"`

	// DeletePasswordlessDevicesAfterResetPassword Whether passwordless (WebAuthn) devices are deleted when the password is reset.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	DeletePasswordlessDevicesAfterResetPassword *bool `json:"deletePasswordlessDevicesAfterResetPassword,omitempty"`

	// DynamicUserRegistration Whether dynamic (self-service) user registration is enabled.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	DynamicUserRegistration *bool `json:"dynamicUserRegistration,omitempty"`

	// Inherited Whether account settings are inherited from the parent (domain). When true, the other fields are ignored. Has no effect when applied to domains.
	// +kubebuilder:validation:Optional
	// Defaults to true.
	Inherited *bool `json:"inherited,omitempty"`

	// LoginAttemptsDetectionEnabled Whether brute-force authentication attempts are detected and blocked.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	LoginAttemptsDetectionEnabled *bool `json:"loginAttemptsDetectionEnabled,omitempty"`

	// LoginAttemptsResetTime Time, in seconds, after which the login attempt counter is reset when the maximum has not been reached.
	// +kubebuilder:validation:Optional
	LoginAttemptsResetTime *int32 `json:"loginAttemptsResetTime,omitempty"`

	// MaxLoginAttempts Maximum number of failed login attempts before the account is blocked.
	// +kubebuilder:validation:Optional
	MaxLoginAttempts *int32 `json:"maxLoginAttempts,omitempty"`

	// MfaChallengeAttemptsDetectionEnabled Whether failed MFA challenge attempts are detected and blocked.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	MfaChallengeAttemptsDetectionEnabled *bool `json:"mfaChallengeAttemptsDetectionEnabled,omitempty"`

	// MfaChallengeAttemptsResetTime Time, in seconds, after which the MFA challenge attempt counter is reset.
	// +kubebuilder:validation:Optional
	MfaChallengeAttemptsResetTime *int32 `json:"mfaChallengeAttemptsResetTime,omitempty"`

	// MfaChallengeMaxAttempts Maximum number of failed MFA challenge attempts before the user is blocked.
	// +kubebuilder:validation:Optional
	MfaChallengeMaxAttempts *int32 `json:"mfaChallengeMaxAttempts,omitempty"`

	// MfaChallengeSendVerifyAlertEmail Whether to send an alert email after too many failed MFA challenge attempts.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	MfaChallengeSendVerifyAlertEmail *bool `json:"mfaChallengeSendVerifyAlertEmail,omitempty"`

	// RedirectUriAfterRegistration URL the user is redirected to after registration.
	// +kubebuilder:validation:Optional
	RedirectUriAfterRegistration *string `json:"redirectUriAfterRegistration,omitempty"`

	// RedirectUriAfterResetPassword URL the user is redirected to after a password reset.
	// +kubebuilder:validation:Optional
	RedirectUriAfterResetPassword *string `json:"redirectUriAfterResetPassword,omitempty"`

	// RememberMe Whether users can remain logged in for a fixed duration (remember-me).
	// +kubebuilder:validation:Optional
	// Defaults to false.
	RememberMe *bool `json:"rememberMe,omitempty"`

	// RememberMeDuration Duration, in seconds, for which a remembered session stays valid.
	// +kubebuilder:validation:Optional
	RememberMeDuration *int32 `json:"rememberMeDuration,omitempty"`

	// ResetPasswordConfirmIdentity Whether the user must confirm their identity before resetting a password.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	ResetPasswordConfirmIdentity *bool `json:"resetPasswordConfirmIdentity,omitempty"`

	// ResetPasswordCustomForm Whether a custom form is used for the password-reset step.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	ResetPasswordCustomForm *bool `json:"resetPasswordCustomForm,omitempty"`

	// ResetPasswordCustomFormFields Custom fields rendered on the password-reset form.
	// +kubebuilder:validation:Optional
	ResetPasswordCustomFormFields []FormField `json:"resetPasswordCustomFormFields,omitempty"`

	// ResetPasswordInvalidateTokens Whether existing tokens are invalidated when the password is reset.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	ResetPasswordInvalidateTokens *bool `json:"resetPasswordInvalidateTokens,omitempty"`

	// SendRecoverAccountEmail Whether to send an account-recovery email.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	SendRecoverAccountEmail *bool `json:"sendRecoverAccountEmail,omitempty"`

	// SendVerifyRegistrationAccountEmail Whether to send a registration-verification email.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	SendVerifyRegistrationAccountEmail *bool `json:"sendVerifyRegistrationAccountEmail,omitempty"`
}

// AutomationCIBASettings Client-Initiated Backchannel Authentication (CIBA) settings for the domain. CIBA lets a relying party initiate end-user authentication from a separate consumption device, without redirecting the user through the browser. Authentication device notifiers are not managed by the Automation API and are not exposed here.
type AutomationCIBASettings = CIBASettings

// CIBASettings Client-Initiated Backchannel Authentication (CIBA) settings for the domain. CIBA lets a relying party initiate end-user authentication from a separate consumption device, without redirecting the user through the browser. Authentication device notifiers are not managed by the Automation API and are not exposed here.
type CIBASettings struct {
	// AuthReqExpiry Default validity period, in seconds, of the issued auth_req_id.
	// +kubebuilder:validation:Optional
	AuthReqExpiry *int32 `json:"authReqExpiry,omitempty"`

	// BindingMessageLength Maximum number of characters accepted for the binding_message parameter.
	// +kubebuilder:validation:Optional
	BindingMessageLength *int32 `json:"bindingMessageLength,omitempty"`

	// Enabled Whether Client-Initiated Backchannel Authentication is enabled for the domain.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	Enabled *bool `json:"enabled,omitempty"`

	// TokenReqInterval Minimum delay, in seconds, that a client must wait between two polls of the token endpoint for the same auth_req_id (POLL or PING delivery mode).
	// +kubebuilder:validation:Optional
	TokenReqInterval *int32 `json:"tokenReqInterval,omitempty"`
}

// AutomationCertificateSettings Domain-level certificate settings.
type AutomationCertificateSettings = CertificateSettings

// CertificateSettings Domain-level certificate settings.
type CertificateSettings struct {
	// FallbackCertificate Key of a certificate managed under this domain, used as the fallback certificate when a client does not specify one. Must reference a certificate created via the domain's certificate endpoints.
	// +kubebuilder:validation:Optional
	FallbackCertificate *string `json:"fallbackCertificate,omitempty"`
}

// AutomationClientRegistrationSettings OpenID Connect Dynamic Client Registration configuration for the domain.
type AutomationClientRegistrationSettings = ClientRegistrationSettings

// ClientRegistrationSettings OpenID Connect Dynamic Client Registration configuration for the domain.
type ClientRegistrationSettings struct {
	// AllowHttpSchemeRedirectUri Whether the unsecured http scheme is permitted in redirect URIs.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	AllowHttpSchemeRedirectUri *bool `json:"allowHttpSchemeRedirectUri,omitempty"`

	// AllowLocalhostRedirectUri Whether localhost is permitted as a redirect URI host.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	AllowLocalhostRedirectUri *bool `json:"allowLocalhostRedirectUri,omitempty"`

	// AllowRedirectUriParamsExpressionLanguage Whether expression language is permitted in redirect URI parameters.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	AllowRedirectUriParamsExpressionLanguage *bool `json:"allowRedirectUriParamsExpressionLanguage,omitempty"`

	// AllowWildCardRedirectUri Whether wildcards are permitted in redirect URIs.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	AllowWildCardRedirectUri *bool `json:"allowWildCardRedirectUri,omitempty"`

	// AllowedScopes Scopes permitted on client registration requests when the allowed list is enabled.
	// +kubebuilder:validation:Optional
	AllowedScopes []string `json:"allowedScopes,omitempty"`

	// AllowedScopesEnabled Whether registered client scopes are restricted to an allowed list.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	AllowedScopesEnabled *bool `json:"allowedScopesEnabled,omitempty"`

	// ClientTemplateEnabled Whether a client may be used as a template for dynamic client registration.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	ClientTemplateEnabled *bool `json:"clientTemplateEnabled,omitempty"`

	// DefaultScopes Default scopes added to every client registration request.
	// +kubebuilder:validation:Optional
	DefaultScopes []string `json:"defaultScopes,omitempty"`

	// DynamicClientRegistrationEnabled Whether Dynamic Client Registration is enabled for the domain.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	DynamicClientRegistrationEnabled *bool `json:"dynamicClientRegistrationEnabled,omitempty"`

	// OpenDynamicClientRegistrationEnabled Whether open (unauthenticated) Dynamic Client Registration is enabled for the domain.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	OpenDynamicClientRegistrationEnabled *bool `json:"openDynamicClientRegistrationEnabled,omitempty"`
}

// AutomationDomain A security domain managed by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update. Certificates, identity providers, and reporters are not embedded; they are managed via the domain's sub-resource endpoints and referenced here by key.
type AutomationDomain = Domain

// Domain A security domain managed by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update. Certificates, identity providers, and reporters are not embedded; they are managed via the domain's sub-resource endpoints and referenced here by key.
type Domain struct {
	// AccountSettings User account settings for the domain: brute-force protection, registration, password reset, remember-me, and MFA challenge behavior.
	AccountSettings *AutomationAccountSettings `json:"accountSettings,omitempty"`

	// AlertEnabled Whether alerting is enabled for the domain.
	// +kubebuilder:validation:Optional
	AlertEnabled *bool `json:"alertEnabled,omitempty"`

	// CertificateSettings Domain-level certificate settings.
	CertificateSettings *AutomationCertificateSettings `json:"certificateSettings,omitempty"`

	// CorsSettings Cross-Origin Resource Sharing configuration controlling which web origins may call the domain's endpoints from a browser.
	CorsSettings *CorsSettings `json:"corsSettings,omitempty"`

	// DataPlaneId Identifier of the data plane this domain is connected to. Optional at creation and resolved from the environment's data planes when omitted. Immutable afterwards: an apply that names a different one is rejected.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:MaxLength=255
	DataPlaneId *string `json:"dataPlaneId,omitempty"`

	// Description Human-readable description of the domain.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty"`

	// Enabled Whether the domain handles incoming authentication and authorization requests.
	// +kubebuilder:validation:Optional
	// Defaults to true.
	// +kubebuilder:default=true
	Enabled *bool `json:"enabled,omitempty"`

	// KeyRetrievalSettings Fetch, SSRF and cache limits applied to every trusted domain in the security domain.
	KeyRetrievalSettings *KeyRetrievalSettings `json:"keyRetrievalSettings,omitempty"`

	// LoginSettings Configuration of the domain's login flow and the features offered on the sign-in page.
	LoginSettings *LoginSettings `json:"loginSettings,omitempty"`

	// Master Whether this is the master domain of its environment. A master domain may perform cross-domain token introspection.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	Master *bool `json:"master,omitempty"`

	// Name Human-readable name of the domain.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=255
	Name string `json:"name"`

	// Oidc OpenID Connect settings for the domain. CIMD (client identity metadata document) settings are not exposed by the Automation API and are reset on update.
	Oidc *AutomationOidcSettings `json:"oidc,omitempty"`

	// PasswordSettings Password policy applied to users of the domain: complexity requirements, expiry, and history.
	PasswordSettings *PasswordSettings `json:"passwordSettings,omitempty"`

	// Path Context path the domain is served under, relative to the gateway. Must start with a slash.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=255
	// +kubebuilder:validation:Pattern=`^/.*`
	Path string `json:"path"`

	// Saml Settings for the domain acting as a SAML 2.0 identity provider (IdP).
	Saml *AutomationSamlSettings `json:"saml,omitempty"`

	// Scim Configuration of the domain's SCIM 2.0 provisioning endpoints.
	Scim *SCIMSettings `json:"scim,omitempty"`

	// SecretExpirationSettings Controls whether client secrets in the domain expire and after how long.
	SecretExpirationSettings *SecretExpirationSettings `json:"secretExpirationSettings,omitempty"`

	// SelfServiceAccountManagementSettings Controls whether end users can manage their own account (for example, reset their password) and the rules that apply.
	SelfServiceAccountManagementSettings *SelfServiceAccountManagementSettings `json:"selfServiceAccountManagementSettings,omitempty"`

	// Tags Sharding tags that control which gateways deploy this domain.
	// +kubebuilder:validation:Optional
	// +listType=set
	Tags []string `json:"tags,omitempty"`

	// TokenExchangeSettings OAuth 2.0 Token Exchange (RFC 8693) configuration for the domain, covering impersonation and delegation.
	TokenExchangeSettings *TokenExchangeSettings `json:"tokenExchangeSettings,omitempty"`

	// Uma Configuration of the domain's User-Managed Access (UMA 2.0) authorization features.
	Uma *UMASettings `json:"uma,omitempty"`

	// VhostMode Whether the domain is exposed through its virtual hosts rather than the default context path. When true, vhosts must be supplied.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	VhostMode *bool `json:"vhostMode,omitempty"`

	// Vhosts Virtual hosts the domain is exposed on, overriding the default context path.
	// +kubebuilder:validation:Optional
	Vhosts []VirtualHost `json:"vhosts,omitempty"`

	// WebAuthnSettings WebAuthn (FIDO2) relying-party configuration governing passwordless and multi-factor authentication for the domain.
	WebAuthnSettings *WebAuthnSettings `json:"webAuthnSettings,omitempty"`

	// WebProtectionSettings HTTP security headers applied to the domain's login and consent pages.
	WebProtectionSettings *WebProtectionSettings `json:"webProtectionSettings,omitempty"`
}

// AutomationOidcSettings OpenID Connect settings for the domain. CIMD (client identity metadata document) settings are not exposed by the Automation API and are reset on update.
type AutomationOidcSettings = OidcSettings

// OidcSettings OpenID Connect settings for the domain. CIMD (client identity metadata document) settings are not exposed by the Automation API and are reset on update.
type OidcSettings struct {
	// CibaSettings Client-Initiated Backchannel Authentication (CIBA) settings for the domain. CIBA lets a relying party initiate end-user authentication from a separate consumption device, without redirecting the user through the browser. Authentication device notifiers are not managed by the Automation API and are not exposed here.
	CibaSettings *AutomationCIBASettings `json:"cibaSettings,omitempty"`

	// ClientRegistrationSettings OpenID Connect Dynamic Client Registration configuration for the domain.
	ClientRegistrationSettings *AutomationClientRegistrationSettings `json:"clientRegistrationSettings,omitempty"`

	// PostLogoutRedirectUris URLs the user may be redirected to after sign-out (post_logout_redirect_uri).
	// +kubebuilder:validation:Optional
	PostLogoutRedirectUris []string `json:"postLogoutRedirectUris,omitempty"`

	// RedirectUriStrictMatching Whether redirect_uri and post_logout_redirect_uri values are matched strictly during OpenID Connect flows.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	RedirectUriStrictMatching *bool `json:"redirectUriStrictMatching,omitempty"`

	// RequestUris Allowed request_uri values for passing OpenID Connect request objects by reference.
	// +kubebuilder:validation:Optional
	RequestUris []string `json:"requestUris,omitempty"`

	// SecurityProfileSettings Financial-grade API (FAPI) security profile configuration for the domain.
	SecurityProfileSettings *SecurityProfileSettings `json:"securityProfileSettings,omitempty"`

	// WorkloadIdentitySettings Workload identity (SPIFFE) settings for the domain.
	WorkloadIdentitySettings *SpiffeDomainSettings `json:"workloadIdentitySettings,omitempty"`
}

// AutomationSamlSettings Settings for the domain acting as a SAML 2.0 identity provider (IdP).
type AutomationSamlSettings = SamlSettings

// SamlSettings Settings for the domain acting as a SAML 2.0 identity provider (IdP).
type SamlSettings struct {
	// Certificate Key of a certificate managed under this domain, used to sign SAML responses. Must reference a certificate created via the domain's certificate endpoints.
	// +kubebuilder:validation:Optional
	Certificate *string `json:"certificate,omitempty"`

	// Enabled Whether the domain exposes the SAML 2.0 IdP protocol.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	Enabled *bool `json:"enabled,omitempty"`

	// EntityId URL or URN that uniquely identifies this IdP (the SAML entity ID).
	// +kubebuilder:validation:Optional
	EntityId *string `json:"entityId,omitempty"`
}

// CorsSettings Cross-Origin Resource Sharing configuration controlling which web origins may call the domain's endpoints from a browser.
type CorsSettings struct {
	// AllowCredentials Whether the browser may send credentials (cookies, authorization headers) with cross-origin requests.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	AllowCredentials *bool `json:"allowCredentials,omitempty"`

	// AllowedHeaders Request headers permitted on cross-origin requests.
	// +kubebuilder:validation:Optional
	// +listType=set
	AllowedHeaders []string `json:"allowedHeaders,omitempty"`

	// AllowedMethods HTTP methods permitted on cross-origin requests.
	// +kubebuilder:validation:Optional
	// +listType=set
	AllowedMethods []string `json:"allowedMethods,omitempty"`

	// AllowedOrigins Origins permitted to make cross-origin requests. Use "*" to allow any origin.
	// +kubebuilder:validation:Optional
	// +listType=set
	AllowedOrigins []string `json:"allowedOrigins,omitempty"`

	// Enabled Whether CORS handling is enabled for the domain when not inherited.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	Enabled *bool `json:"enabled,omitempty"`

	// Inherited Whether CORS settings are inherited from the gateway defaults (gravitee.yml). When null, legacy behaviour applies: enabled=true overrides and enabled=false inherits.
	// +kubebuilder:validation:Optional
	// Defaults to true.
	Inherited *bool `json:"inherited,omitempty"`

	// MaxAge How long, in seconds, a browser may cache the result of a preflight request.
	// +kubebuilder:validation:Optional
	// Defaults to 86400.
	MaxAge *int32 `json:"maxAge,omitempty"`
}

// CspSettings Content Security Policy configuration for the domain's login and consent pages.
type CspSettings struct {
	// Directives CSP directives, one per entry, in the form "directive-name value". A trailing semicolon is optional. Directive names must be valid CSP tokens and must not repeat; values are not interpreted. Directives that take no value, such as "upgrade-insecure-requests", may be supplied on their own. When reportOnly is enabled, a "report-uri" or "report-to" directive is required.
	// +kubebuilder:validation:Optional
	Directives []string `json:"directives,omitempty"`

	// Enabled Whether CSP is enabled for the domain when not inherited.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	Enabled *bool `json:"enabled,omitempty"`

	// Inherited Whether CSP settings are inherited from the gateway defaults (gravitee.yml). When null, legacy behaviour applies: enabled=true overrides and enabled=false inherits.
	// +kubebuilder:validation:Optional
	// Defaults to true.
	Inherited *bool `json:"inherited,omitempty"`

	// ReportOnly When true, the policy is delivered as Content-Security-Policy-Report-Only.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	ReportOnly *bool `json:"reportOnly,omitempty"`

	// ScriptInlineNonce Whether inline scripts are allowed via a per-request nonce.
	// +kubebuilder:validation:Optional
	// Defaults to true.
	ScriptInlineNonce *bool `json:"scriptInlineNonce,omitempty"`
}

// FormField A single field shown on a user-facing form, such as registration.
type FormField struct {
	// Key Identifier of the field, mapped to a user attribute.
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty"`

	// Label Label displayed for the field.
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty"`

	// Type Input type of the field.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty"`
}

// IdJagSettings ID-JAG issuance behavior of token exchange.
type IdJagSettings struct {
	// LaxValidation Lax validation: also accept an access token issued to the requesting client as the subject token. By default only an ID token is accepted.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	LaxValidation *bool `json:"laxValidation,omitempty"`
}

// KeyRetrievalSettings Fetch, SSRF and cache limits applied to every trusted domain in the security domain.
type KeyRetrievalSettings struct {
	// AllowPrivateIpAddress Whether key material can be fetched from private IP addresses.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	AllowPrivateIpAddress *bool `json:"allowPrivateIpAddress,omitempty"`

	// AllowUnsecuredHttpUri Whether key material can be fetched over unsecured HTTP URIs.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	AllowUnsecuredHttpUri *bool `json:"allowUnsecuredHttpUri,omitempty"`

	// CacheMaxEntries Maximum number of key material entries retained in the cache.
	// +kubebuilder:validation:Optional
	// Defaults to 50.
	CacheMaxEntries *int32 `json:"cacheMaxEntries,omitempty"`

	// CacheTtlSeconds Time-to-live, in seconds, for cached key material.
	// +kubebuilder:validation:Optional
	// Defaults to 300.
	CacheTtlSeconds *int32 `json:"cacheTtlSeconds,omitempty"`

	// FetchTimeoutMs Timeout, in milliseconds, for fetching key material.
	// +kubebuilder:validation:Optional
	// Defaults to 5000.
	FetchTimeoutMs *int32 `json:"fetchTimeoutMs,omitempty"`

	// MaxResponseSizeKb Maximum key material response size, in kilobytes.
	// +kubebuilder:validation:Optional
	// Defaults to 32.
	MaxResponseSizeKb *int32 `json:"maxResponseSizeKb,omitempty"`
}

// LoginSettings Configuration of the domain's login flow and the features offered on the sign-in page.
type LoginSettings struct {
	// CertificateBasedAuthEnabled Whether certificate-based authentication is offered.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	CertificateBasedAuthEnabled *bool `json:"certificateBasedAuthEnabled,omitempty"`

	// CertificateBasedAuthUrl URL used for certificate-based authentication.
	// +kubebuilder:validation:Optional
	CertificateBasedAuthUrl *string `json:"certificateBasedAuthUrl,omitempty"`

	// ForgotPasswordEnabled Whether users can initiate a forgot-password flow from the login page.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	ForgotPasswordEnabled *bool `json:"forgotPasswordEnabled,omitempty"`

	// HideForm Whether the login form is hidden (for example when only social or identifier-first login is offered).
	// +kubebuilder:validation:Optional
	// Defaults to false.
	HideForm *bool `json:"hideForm,omitempty"`

	// IdentifierFirstEnabled Whether identifier-first login is enabled, prompting for the username before the password.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	IdentifierFirstEnabled *bool `json:"identifierFirstEnabled,omitempty"`

	// Inherited Whether these login settings are inherited from a parent scope rather than defined here. When true, the other fields are ignored.
	// +kubebuilder:validation:Optional
	// Defaults to true.
	Inherited *bool `json:"inherited,omitempty"`

	// MagicLinkAuthEnabled Whether magic-link authentication is offered.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	MagicLinkAuthEnabled *bool `json:"magicLinkAuthEnabled,omitempty"`

	// PasswordlessDeviceNamingEnabled Whether users can name their passwordless devices.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	PasswordlessDeviceNamingEnabled *bool `json:"passwordlessDeviceNamingEnabled,omitempty"`

	// PasswordlessEnabled Whether passwordless (WebAuthn) authentication is offered.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	PasswordlessEnabled *bool `json:"passwordlessEnabled,omitempty"`

	// PasswordlessEnforcePasswordEnabled Whether a password is still required alongside passwordless authentication.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	PasswordlessEnforcePasswordEnabled *bool `json:"passwordlessEnforcePasswordEnabled,omitempty"`

	// PasswordlessEnforcePasswordMaxAge Period, in seconds, after which the user's credentials must be re-entered to keep using passwordless authentication.
	// +kubebuilder:validation:Optional
	PasswordlessEnforcePasswordMaxAge *int32 `json:"passwordlessEnforcePasswordMaxAge,omitempty"`

	// PasswordlessRememberDeviceEnabled Whether a passwordless device can be remembered to skip future challenges.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	PasswordlessRememberDeviceEnabled *bool `json:"passwordlessRememberDeviceEnabled,omitempty"`

	// RegisterEnabled Whether users can self-register from the login page.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	RegisterEnabled *bool `json:"registerEnabled,omitempty"`

	// RememberMeEnabled Whether the login page offers a remember-me option.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	RememberMeEnabled *bool `json:"rememberMeEnabled,omitempty"`

	// ResetPasswordOnExpiration Whether the user is forced to reset their password once it expires.
	// +kubebuilder:validation:Optional
	ResetPasswordOnExpiration *bool `json:"resetPasswordOnExpiration,omitempty"`
}

// PasswordSettings Password policy applied to users of the domain: complexity requirements, expiry, and history.
type PasswordSettings struct {
	// ExcludePasswordsInDictionary Whether passwords found in a common-password dictionary are rejected.
	// +kubebuilder:validation:Optional
	ExcludePasswordsInDictionary *bool `json:"excludePasswordsInDictionary,omitempty"`

	// ExcludeUserProfileInfoInPassword Whether passwords containing the user's profile information are rejected.
	// +kubebuilder:validation:Optional
	ExcludeUserProfileInfoInPassword *bool `json:"excludeUserProfileInfoInPassword,omitempty"`

	// ExpiryDuration Number of days after which a password expires and must be changed.
	// +kubebuilder:validation:Optional
	ExpiryDuration *int32 `json:"expiryDuration,omitempty"`

	// IncludeNumbers Whether a password must contain at least one number.
	// +kubebuilder:validation:Optional
	IncludeNumbers *bool `json:"includeNumbers,omitempty"`

	// IncludeSpecialCharacters Whether a password must contain at least one special character.
	// +kubebuilder:validation:Optional
	IncludeSpecialCharacters *bool `json:"includeSpecialCharacters,omitempty"`

	// Inherited Whether these password settings are inherited from a parent scope rather than defined here. When true, the other fields are ignored.
	// +kubebuilder:validation:Optional
	// Defaults to true.
	Inherited *bool `json:"inherited,omitempty"`

	// LettersInMixedCase Whether a password must contain both uppercase and lowercase letters.
	// +kubebuilder:validation:Optional
	LettersInMixedCase *bool `json:"lettersInMixedCase,omitempty"`

	// MaxConsecutiveLetters Maximum number of identical consecutive characters allowed in a password.
	// +kubebuilder:validation:Optional
	MaxConsecutiveLetters *int32 `json:"maxConsecutiveLetters,omitempty"`

	// MaxLength Maximum number of characters a password may contain.
	// +kubebuilder:validation:Optional
	// Defaults to 128.
	MaxLength *int32 `json:"maxLength,omitempty"`

	// MinLength Minimum number of characters a password must contain.
	// +kubebuilder:validation:Optional
	// Defaults to 8.
	MinLength *int32 `json:"minLength,omitempty"`

	// OldPasswords Number of previous passwords retained in history and barred from reuse.
	// +kubebuilder:validation:Optional
	OldPasswords *int32 `json:"oldPasswords,omitempty"`

	// PasswordHistoryEnabled Whether password history is enforced to prevent reuse of recent passwords.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	PasswordHistoryEnabled *bool `json:"passwordHistoryEnabled,omitempty"`
}

// ResetPasswordSettings Rules applied to a self-service password reset.
type ResetPasswordSettings struct {
	// OldPasswordRequired Whether the user must supply their current password to set a new one.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	OldPasswordRequired *bool `json:"oldPasswordRequired,omitempty"`

	// TokenAge Lifetime, in seconds, of the password-reset token.
	// +kubebuilder:validation:Optional
	TokenAge *int32 `json:"tokenAge,omitempty"`
}

// SCIMSettings Configuration of the domain's SCIM 2.0 provisioning endpoints.
type SCIMSettings struct {
	// Enabled Whether the SCIM provisioning API is enabled for the domain.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	Enabled *bool `json:"enabled,omitempty"`

	// IdpSelectionEnabled Whether an identity provider is selected for SCIM-provisioned users using a selection rule.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	IdpSelectionEnabled *bool `json:"idpSelectionEnabled,omitempty"`

	// IdpSelectionRule Expression that selects the identity provider for a SCIM-provisioned user.
	// +kubebuilder:validation:Optional
	IdpSelectionRule *string `json:"idpSelectionRule,omitempty"`
}

// SecretExpirationSettings Controls whether client secrets in the domain expire and after how long.
type SecretExpirationSettings struct {
	// Enabled Whether client-secret expiration is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty"`

	// ExpiryTimeSeconds Lifetime, in seconds, of a client secret before it expires.
	// +kubebuilder:validation:Optional
	ExpiryTimeSeconds *int64 `json:"expiryTimeSeconds,omitempty"`
}

// SecurityProfileSettings Financial-grade API (FAPI) security profile configuration for the domain.
type SecurityProfileSettings struct {
	// EnableFapiBrazil Whether the Open Banking Brasil Financial-grade API security profile (version 1.0) is applied.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	EnableFapiBrazil *bool `json:"enableFapiBrazil,omitempty"`

	// EnablePlainFapi Whether the standard Financial-grade API security profile (version 1.0) is applied.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	EnablePlainFapi *bool `json:"enablePlainFapi,omitempty"`
}

// SelfServiceAccountManagementSettings Controls whether end users can manage their own account (for example, reset their password) and the rules that apply.
type SelfServiceAccountManagementSettings struct {
	// Enabled Whether self-service account management is enabled for end users.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	Enabled *bool `json:"enabled,omitempty"`

	// ResetPassword Rules applied to a self-service password reset.
	ResetPassword *ResetPasswordSettings `json:"resetPassword,omitempty"`
}

// SpiffeDomainSettings Workload identity (SPIFFE) settings for the domain.
type SpiffeDomainSettings struct {
	// AllowPrivateIpAddress Deprecated: moved to keyRetrievalSettings.allowPrivateIpAddress.
	// +kubebuilder:validation:Optional
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	AllowPrivateIpAddress *bool `json:"allowPrivateIpAddress,omitempty"`

	// AllowUnsecuredHttpUri Deprecated: moved to keyRetrievalSettings.allowUnsecuredHttpUri.
	// +kubebuilder:validation:Optional
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	AllowUnsecuredHttpUri *bool `json:"allowUnsecuredHttpUri,omitempty"`

	// CacheMaxEntries Deprecated: moved to keyRetrievalSettings.cacheMaxEntries.
	// +kubebuilder:validation:Optional
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	CacheMaxEntries *int32 `json:"cacheMaxEntries,omitempty"`

	// CacheTtlSeconds Deprecated: moved to keyRetrievalSettings.cacheTtlSeconds.
	// +kubebuilder:validation:Optional
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	CacheTtlSeconds *int32 `json:"cacheTtlSeconds,omitempty"`

	// ClockSkewSeconds Allowed clock skew, in seconds, when validating JWT temporal claims.
	// +kubebuilder:validation:Optional
	// Defaults to 30.
	ClockSkewSeconds *int32 `json:"clockSkewSeconds,omitempty"`

	// DefaultAllowedAlgorithms Default allowlist of signature algorithms accepted for SPIFFE JWT validation.
	// +kubebuilder:validation:Optional
	DefaultAllowedAlgorithms []string `json:"defaultAllowedAlgorithms,omitempty"`

	// Enabled Whether SPIFFE workload identity support is enabled for the domain.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	Enabled *bool `json:"enabled,omitempty"`

	// FetchTimeoutMs Deprecated: moved to keyRetrievalSettings.fetchTimeoutMs.
	// +kubebuilder:validation:Optional
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	FetchTimeoutMs *int32 `json:"fetchTimeoutMs,omitempty"`

	// MaxJwtLifetimeSeconds Maximum accepted JWT lifetime, in seconds, computed as exp minus iat.
	// +kubebuilder:validation:Optional
	// Defaults to 300.
	MaxJwtLifetimeSeconds *int32 `json:"maxJwtLifetimeSeconds,omitempty"`

	// MaxResponseSizeKb Deprecated: moved to keyRetrievalSettings.maxResponseSizeKb.
	// +kubebuilder:validation:Optional
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	MaxResponseSizeKb *int32 `json:"maxResponseSizeKb,omitempty"`
}

// TokenExchangeOAuthSettings OAuth-specific token-exchange behavior, such as how scopes are handled, with optional inheritance from domain defaults.
type TokenExchangeOAuthSettings struct {
	// Inherited Whether these settings are inherited from the domain defaults rather than defined here.
	// +kubebuilder:validation:Optional
	// Defaults to true.
	Inherited *bool `json:"inherited,omitempty"`

	// ScopeHandling How scopes are handled when issuing the exchanged token. DOWNSCOPING restricts the issued token to a subset of the original scopes.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Enum=downscoping;permissive
	// Defaults to downscoping.
	ScopeHandling *string `json:"scopeHandling,omitempty"`
}

// TokenExchangeSettings OAuth 2.0 Token Exchange (RFC 8693) configuration for the domain, covering impersonation and delegation.
type TokenExchangeSettings struct {
	// AllowDelegation Whether delegation is allowed, where an actor acts on behalf of the subject and an "act" claim is added to the issued token. At least one of allowImpersonation or allowDelegation must be enabled.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	AllowDelegation *bool `json:"allowDelegation,omitempty"`

	// AllowImpersonation Whether impersonation is allowed, where the issued token represents the subject directly. At least one of allowImpersonation or allowDelegation must be enabled.
	// +kubebuilder:validation:Optional
	// Defaults to true.
	AllowImpersonation *bool `json:"allowImpersonation,omitempty"`

	// AllowedActorTokenTypes Token types accepted as the actor token when delegating.
	// +kubebuilder:validation:Optional
	AllowedActorTokenTypes []string `json:"allowedActorTokenTypes,omitempty"`

	// AllowedRequestedTokenTypes Token types that may be requested as the result of an exchange.
	// +kubebuilder:validation:Optional
	AllowedRequestedTokenTypes []string `json:"allowedRequestedTokenTypes,omitempty"`

	// AllowedSubjectTokenTypes Token types accepted as the subject token in an exchange.
	// +kubebuilder:validation:Optional
	AllowedSubjectTokenTypes []string `json:"allowedSubjectTokenTypes,omitempty"`

	// Enabled Whether token exchange is enabled for the domain.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	Enabled *bool `json:"enabled,omitempty"`

	// IdJagSettings ID-JAG issuance behavior of token exchange.
	IdJagSettings *IdJagSettings `json:"idJagSettings,omitempty"`

	// MaxDelegationDepth Maximum depth of the delegation chain (nested "act" claims). Clamped to the range 1–100.
	// +kubebuilder:validation:Optional
	// Defaults to 25.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:validation:Maximum=100
	MaxDelegationDepth *int32 `json:"maxDelegationDepth,omitempty"`

	// TokenExchangeOAuthSettings OAuth-specific token-exchange behavior, such as how scopes are handled, with optional inheritance from domain defaults.
	TokenExchangeOAuthSettings *TokenExchangeOAuthSettings `json:"tokenExchangeOAuthSettings,omitempty"`

	// TrustedIssuers Deprecated: use the trusted-domains API instead. External issuers whose JWTs may be accepted as subject or actor tokens. A projection over the security domain's token-exchange trusted domains; a write replaces the list, so an omitted issuer is no longer trusted.
	// +kubebuilder:validation:Optional
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	TrustedIssuers []TrustedIssuer `json:"trustedIssuers,omitempty"`
}

// TrustedIssuer An external token issuer whose JWTs are accepted as subject or actor tokens during token exchange, validated with the configured key material.
//
// Deprecated: this type has been marked as deprecated upstream, but no `x-deprecated-reason` was set
type TrustedIssuer struct {
	// Certificate PEM-encoded X.509 certificate. Required when keyResolutionMethod is PEM.
	// +kubebuilder:validation:Optional
	Certificate *string `json:"certificate,omitempty"`

	// Issuer Expected value of the "iss" claim in the external JWT.
	// +kubebuilder:validation:Optional
	Issuer *string `json:"issuer,omitempty"`

	// JwksUri JWKS endpoint URL. Required when keyResolutionMethod is JWKS_URL.
	// +kubebuilder:validation:Optional
	JwksUri *string `json:"jwksUri,omitempty"`

	// KeyResolutionMethod How the issuer's signing key is resolved. JWKS_URL fetches keys from a JWKS endpoint; PEM uses an inline X.509 certificate.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Enum=jwks_url;pem
	KeyResolutionMethod *string `json:"keyResolutionMethod,omitempty"`

	// ScopeMappings One-to-one mapping from external scope to domain scope. Unmapped issuer scopes are dropped (fail-closed).
	// +kubebuilder:validation:Optional
	ScopeMappings map[string]string `json:"scopeMappings,omitempty"`

	// UserBindingCriteria Criteria used to locate a domain user when user binding is enabled. All criteria are combined with AND.
	// +kubebuilder:validation:Optional
	UserBindingCriteria []UserBindingCriterion `json:"userBindingCriteria,omitempty"`

	// UserBindingEnabled Whether the external JWT subject is resolved to a single domain user using the user binding criteria. When false, a virtual user is built from the token claims only.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	UserBindingEnabled *bool `json:"userBindingEnabled,omitempty"`
}

// UMASettings Configuration of the domain's User-Managed Access (UMA 2.0) authorization features.
type UMASettings struct {
	// Enabled Whether User-Managed Access is enabled for the domain.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	Enabled *bool `json:"enabled,omitempty"`
}

// UserBindingCriterion A single rule that matches a domain user attribute against a value derived from the external token claims.
type UserBindingCriterion struct {
	// Attribute Domain user attribute used for the lookup. Must match a field supported by the user repository search.
	// +kubebuilder:validation:Optional
	Attribute *string `json:"attribute,omitempty"`

	// Expression Expression evaluated against the validated token claims (variable "token") to produce the value to match.
	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty"`
}

// VirtualHost A host and path the domain is exposed on. The host and path combination must be unique across all domains.
type VirtualHost struct {
	// Host Hostname the domain is served on.
	// +kubebuilder:validation:Optional
	Host *string `json:"host,omitempty"`

	// OverrideEntrypoint Whether this virtual host overrides the organization entry point.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	OverrideEntrypoint *bool `json:"overrideEntrypoint,omitempty"`

	// Path Context path the domain is served under on this host.
	// +kubebuilder:validation:Optional
	Path *string `json:"path,omitempty"`
}

// WebAuthnSettings WebAuthn (FIDO2) relying-party configuration governing passwordless and multi-factor authentication for the domain.
type WebAuthnSettings struct {
	// AttestationConveyancePreference Relying-party preference for attestation conveyance during credential creation. NONE requests no attestation, INDIRECT allows anonymized attestation, and DIRECT requests the authenticator's attestation statement.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Enum=none;indirect;direct
	// Defaults to none.
	AttestationConveyancePreference *string `json:"attestationConveyancePreference,omitempty"`

	// AuthenticatorAttachment Preferred authenticator attachment. PLATFORM selects authenticators bound to the device (such as a fingerprint reader); CROSS_PLATFORM selects roaming authenticators (such as a security key).
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Enum=cross_platform;platform
	AuthenticatorAttachment *string `json:"authenticatorAttachment,omitempty"`

	// Certificates Trusted device-attestation X.509 certificates, keyed by name.
	// +kubebuilder:validation:Optional
	Certificates map[string]string `json:"certificates,omitempty"`

	// EnforceAuthenticatorIntegrity Whether to periodically re-verify that registered authenticators remain valid against the FIDO2 Metadata Service.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	EnforceAuthenticatorIntegrity *bool `json:"enforceAuthenticatorIntegrity,omitempty"`

	// EnforceAuthenticatorIntegrityMaxAge Maximum elapsed time, in seconds, since an authenticator was last verified before it is re-checked on the next passwordless login.
	// +kubebuilder:validation:Optional
	EnforceAuthenticatorIntegrityMaxAge *int32 `json:"enforceAuthenticatorIntegrityMaxAge,omitempty"`

	// ForceRegistration Whether to reject registration of a credential already registered to a different user.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	ForceRegistration *bool `json:"forceRegistration,omitempty"`

	// Origin Relying-party origin; must match the browser's window.location.origin during registration and authentication ceremonies.
	// +kubebuilder:validation:Optional
	Origin *string `json:"origin,omitempty"`

	// RelyingPartyId Relying-party identifier: a domain string that scopes credentials to this entity. A credential can only be used with the relying party it was registered against.
	// +kubebuilder:validation:Optional
	RelyingPartyId *string `json:"relyingPartyId,omitempty"`

	// RelyingPartyName Human-readable relying-party name shown to users during ceremonies.
	// +kubebuilder:validation:Optional
	RelyingPartyName *string `json:"relyingPartyName,omitempty"`

	// RequireResidentKey Whether the authenticator must create a client-side resident (discoverable) credential.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	RequireResidentKey *bool `json:"requireResidentKey,omitempty"`

	// UserVerification Relying-party requirement regarding user verification during a ceremony. REQUIRED enforces verification, PREFERRED requests it when available, and DISCOURAGED avoids it.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Enum=required;preferred;discouraged
	// Defaults to preferred.
	UserVerification *string `json:"userVerification,omitempty"`
}

// WebProtectionSettings HTTP security headers applied to the domain's login and consent pages.
type WebProtectionSettings struct {
	// Csp Content Security Policy configuration for the domain's login and consent pages.
	Csp *CspSettings `json:"csp,omitempty"`

	// Xframe Controls whether the domain's pages may be embedded in frames on other origins.
	Xframe *XFrameSettings `json:"xframe,omitempty"`

	// Xss Controls the legacy X-XSS-Protection response header.
	Xss *XssProtectionSettings `json:"xss,omitempty"`
}

// XFrameSettings Controls whether the domain's pages may be embedded in frames on other origins.
type XFrameSettings struct {
	// Action X-Frame-Options action. Supported values: DENY, SAMEORIGIN. Leave empty to omit the header.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Enum=DENY;SAMEORIGIN
	Action *string `json:"action,omitempty"`

	// Enabled Whether X-Frame-Options is enabled for the domain when not inherited.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	Enabled *bool `json:"enabled,omitempty"`

	// Inherited Whether X-Frame-Options settings are inherited from the gateway defaults (gravitee.yml). When null, legacy behaviour applies: enabled=true overrides and enabled=false inherits.
	// +kubebuilder:validation:Optional
	// Defaults to true.
	Inherited *bool `json:"inherited,omitempty"`
}

// XssProtectionSettings Controls the legacy X-XSS-Protection response header.
type XssProtectionSettings struct {
	// Action Value of the X-XSS-Protection header.
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty"`

	// Enabled Whether X-XSS-Protection is enabled for the domain when not inherited.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	Enabled *bool `json:"enabled,omitempty"`

	// Inherited Whether X-XSS-Protection settings are inherited from the gateway defaults (gravitee.yml). When null, legacy behaviour applies: enabled=true overrides and enabled=false inherits.
	// +kubebuilder:validation:Optional
	// Defaults to true.
	Inherited *bool `json:"inherited,omitempty"`
}
