//go:build !ignore_autogenerated

/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package domain

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountSettings) DeepCopyInto(out *AccountSettings) {
	*out = *in
	if in.AccountBlockedDuration != nil {
		in, out := &in.AccountBlockedDuration, &out.AccountBlockedDuration
		*out = new(int32)
		**out = **in
	}
	if in.AutoLoginAfterRegistration != nil {
		in, out := &in.AutoLoginAfterRegistration, &out.AutoLoginAfterRegistration
		*out = new(bool)
		**out = **in
	}
	if in.AutoLoginAfterResetPassword != nil {
		in, out := &in.AutoLoginAfterResetPassword, &out.AutoLoginAfterResetPassword
		*out = new(bool)
		**out = **in
	}
	if in.CompleteRegistrationWhenResetPassword != nil {
		in, out := &in.CompleteRegistrationWhenResetPassword, &out.CompleteRegistrationWhenResetPassword
		*out = new(bool)
		**out = **in
	}
	if in.DefaultIdentityProviderForRegistration != nil {
		in, out := &in.DefaultIdentityProviderForRegistration, &out.DefaultIdentityProviderForRegistration
		*out = new(string)
		**out = **in
	}
	if in.DeletePasswordlessDevicesAfterResetPassword != nil {
		in, out := &in.DeletePasswordlessDevicesAfterResetPassword, &out.DeletePasswordlessDevicesAfterResetPassword
		*out = new(bool)
		**out = **in
	}
	if in.DynamicUserRegistration != nil {
		in, out := &in.DynamicUserRegistration, &out.DynamicUserRegistration
		*out = new(bool)
		**out = **in
	}
	if in.Inherited != nil {
		in, out := &in.Inherited, &out.Inherited
		*out = new(bool)
		**out = **in
	}
	if in.LoginAttemptsDetectionEnabled != nil {
		in, out := &in.LoginAttemptsDetectionEnabled, &out.LoginAttemptsDetectionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LoginAttemptsResetTime != nil {
		in, out := &in.LoginAttemptsResetTime, &out.LoginAttemptsResetTime
		*out = new(int32)
		**out = **in
	}
	if in.MaxLoginAttempts != nil {
		in, out := &in.MaxLoginAttempts, &out.MaxLoginAttempts
		*out = new(int32)
		**out = **in
	}
	if in.MfaChallengeAttemptsDetectionEnabled != nil {
		in, out := &in.MfaChallengeAttemptsDetectionEnabled, &out.MfaChallengeAttemptsDetectionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MfaChallengeAttemptsResetTime != nil {
		in, out := &in.MfaChallengeAttemptsResetTime, &out.MfaChallengeAttemptsResetTime
		*out = new(int32)
		**out = **in
	}
	if in.MfaChallengeMaxAttempts != nil {
		in, out := &in.MfaChallengeMaxAttempts, &out.MfaChallengeMaxAttempts
		*out = new(int32)
		**out = **in
	}
	if in.MfaChallengeSendVerifyAlertEmail != nil {
		in, out := &in.MfaChallengeSendVerifyAlertEmail, &out.MfaChallengeSendVerifyAlertEmail
		*out = new(bool)
		**out = **in
	}
	if in.RedirectUriAfterRegistration != nil {
		in, out := &in.RedirectUriAfterRegistration, &out.RedirectUriAfterRegistration
		*out = new(string)
		**out = **in
	}
	if in.RedirectUriAfterResetPassword != nil {
		in, out := &in.RedirectUriAfterResetPassword, &out.RedirectUriAfterResetPassword
		*out = new(string)
		**out = **in
	}
	if in.RememberMe != nil {
		in, out := &in.RememberMe, &out.RememberMe
		*out = new(bool)
		**out = **in
	}
	if in.RememberMeDuration != nil {
		in, out := &in.RememberMeDuration, &out.RememberMeDuration
		*out = new(int32)
		**out = **in
	}
	if in.ResetPasswordConfirmIdentity != nil {
		in, out := &in.ResetPasswordConfirmIdentity, &out.ResetPasswordConfirmIdentity
		*out = new(bool)
		**out = **in
	}
	if in.ResetPasswordCustomForm != nil {
		in, out := &in.ResetPasswordCustomForm, &out.ResetPasswordCustomForm
		*out = new(bool)
		**out = **in
	}
	if in.ResetPasswordCustomFormFields != nil {
		in, out := &in.ResetPasswordCustomFormFields, &out.ResetPasswordCustomFormFields
		*out = new([]FormField)
		if **in != nil {
			in, out := *in, *out
			*out = make([]FormField, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.ResetPasswordInvalidateTokens != nil {
		in, out := &in.ResetPasswordInvalidateTokens, &out.ResetPasswordInvalidateTokens
		*out = new(bool)
		**out = **in
	}
	if in.SendRecoverAccountEmail != nil {
		in, out := &in.SendRecoverAccountEmail, &out.SendRecoverAccountEmail
		*out = new(bool)
		**out = **in
	}
	if in.SendVerifyRegistrationAccountEmail != nil {
		in, out := &in.SendVerifyRegistrationAccountEmail, &out.SendVerifyRegistrationAccountEmail
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountSettings.
func (in *AccountSettings) DeepCopy() *AccountSettings {
	if in == nil {
		return nil
	}
	out := new(AccountSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CIBASettings) DeepCopyInto(out *CIBASettings) {
	*out = *in
	if in.AuthReqExpiry != nil {
		in, out := &in.AuthReqExpiry, &out.AuthReqExpiry
		*out = new(int32)
		**out = **in
	}
	if in.BindingMessageLength != nil {
		in, out := &in.BindingMessageLength, &out.BindingMessageLength
		*out = new(int32)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.TokenReqInterval != nil {
		in, out := &in.TokenReqInterval, &out.TokenReqInterval
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CIBASettings.
func (in *CIBASettings) DeepCopy() *CIBASettings {
	if in == nil {
		return nil
	}
	out := new(CIBASettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSettings) DeepCopyInto(out *CertificateSettings) {
	*out = *in
	if in.FallbackCertificate != nil {
		in, out := &in.FallbackCertificate, &out.FallbackCertificate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSettings.
func (in *CertificateSettings) DeepCopy() *CertificateSettings {
	if in == nil {
		return nil
	}
	out := new(CertificateSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientRegistrationSettings) DeepCopyInto(out *ClientRegistrationSettings) {
	*out = *in
	if in.AllowHttpSchemeRedirectUri != nil {
		in, out := &in.AllowHttpSchemeRedirectUri, &out.AllowHttpSchemeRedirectUri
		*out = new(bool)
		**out = **in
	}
	if in.AllowLocalhostRedirectUri != nil {
		in, out := &in.AllowLocalhostRedirectUri, &out.AllowLocalhostRedirectUri
		*out = new(bool)
		**out = **in
	}
	if in.AllowRedirectUriParamsExpressionLanguage != nil {
		in, out := &in.AllowRedirectUriParamsExpressionLanguage, &out.AllowRedirectUriParamsExpressionLanguage
		*out = new(bool)
		**out = **in
	}
	if in.AllowWildCardRedirectUri != nil {
		in, out := &in.AllowWildCardRedirectUri, &out.AllowWildCardRedirectUri
		*out = new(bool)
		**out = **in
	}
	if in.AllowedScopes != nil {
		in, out := &in.AllowedScopes, &out.AllowedScopes
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.ClientTemplateEnabled != nil {
		in, out := &in.ClientTemplateEnabled, &out.ClientTemplateEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DynamicClientRegistrationEnabled != nil {
		in, out := &in.DynamicClientRegistrationEnabled, &out.DynamicClientRegistrationEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.OpenDynamicClientRegistrationEnabled != nil {
		in, out := &in.OpenDynamicClientRegistrationEnabled, &out.OpenDynamicClientRegistrationEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientRegistrationSettings.
func (in *ClientRegistrationSettings) DeepCopy() *ClientRegistrationSettings {
	if in == nil {
		return nil
	}
	out := new(ClientRegistrationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorsSettings) DeepCopyInto(out *CorsSettings) {
	*out = *in
	if in.AllowCredentials != nil {
		in, out := &in.AllowCredentials, &out.AllowCredentials
		*out = new(bool)
		**out = **in
	}
	if in.AllowedHeaders != nil {
		in, out := &in.AllowedHeaders, &out.AllowedHeaders
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedMethods != nil {
		in, out := &in.AllowedMethods, &out.AllowedMethods
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedOrigins != nil {
		in, out := &in.AllowedOrigins, &out.AllowedOrigins
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Inherited != nil {
		in, out := &in.Inherited, &out.Inherited
		*out = new(bool)
		**out = **in
	}
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorsSettings.
func (in *CorsSettings) DeepCopy() *CorsSettings {
	if in == nil {
		return nil
	}
	out := new(CorsSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CspSettings) DeepCopyInto(out *CspSettings) {
	*out = *in
	if in.Directives != nil {
		in, out := &in.Directives, &out.Directives
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Inherited != nil {
		in, out := &in.Inherited, &out.Inherited
		*out = new(bool)
		**out = **in
	}
	if in.ReportOnly != nil {
		in, out := &in.ReportOnly, &out.ReportOnly
		*out = new(bool)
		**out = **in
	}
	if in.ScriptInlineNonce != nil {
		in, out := &in.ScriptInlineNonce, &out.ScriptInlineNonce
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CspSettings.
func (in *CspSettings) DeepCopy() *CspSettings {
	if in == nil {
		return nil
	}
	out := new(CspSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Domain) DeepCopyInto(out *Domain) {
	*out = *in
	if in.AccountSettings != nil {
		in, out := &in.AccountSettings, &out.AccountSettings
		*out = new(AccountSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.AlertEnabled != nil {
		in, out := &in.AlertEnabled, &out.AlertEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CertificateSettings != nil {
		in, out := &in.CertificateSettings, &out.CertificateSettings
		*out = new(CertificateSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.CorsSettings != nil {
		in, out := &in.CorsSettings, &out.CorsSettings
		*out = new(CorsSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.DataPlaneId != nil {
		in, out := &in.DataPlaneId, &out.DataPlaneId
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.KeyRetrievalSettings != nil {
		in, out := &in.KeyRetrievalSettings, &out.KeyRetrievalSettings
		*out = new(KeyRetrievalSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.LoginSettings != nil {
		in, out := &in.LoginSettings, &out.LoginSettings
		*out = new(LoginSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Master != nil {
		in, out := &in.Master, &out.Master
		*out = new(bool)
		**out = **in
	}
	if in.Oidc != nil {
		in, out := &in.Oidc, &out.Oidc
		*out = new(OidcSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.PasswordSettings != nil {
		in, out := &in.PasswordSettings, &out.PasswordSettings
		*out = new(PasswordSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Saml != nil {
		in, out := &in.Saml, &out.Saml
		*out = new(SamlSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Scim != nil {
		in, out := &in.Scim, &out.Scim
		*out = new(SCIMSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretExpirationSettings != nil {
		in, out := &in.SecretExpirationSettings, &out.SecretExpirationSettings
		*out = new(SecretExpirationSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.SelfServiceAccountManagementSettings != nil {
		in, out := &in.SelfServiceAccountManagementSettings, &out.SelfServiceAccountManagementSettings
		*out = new(SelfServiceAccountManagementSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.TokenExchangeSettings != nil {
		in, out := &in.TokenExchangeSettings, &out.TokenExchangeSettings
		*out = new(TokenExchangeSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Uma != nil {
		in, out := &in.Uma, &out.Uma
		*out = new(UMASettings)
		(*in).DeepCopyInto(*out)
	}
	if in.VhostMode != nil {
		in, out := &in.VhostMode, &out.VhostMode
		*out = new(bool)
		**out = **in
	}
	if in.Vhosts != nil {
		in, out := &in.Vhosts, &out.Vhosts
		*out = new([]VirtualHost)
		if **in != nil {
			in, out := *in, *out
			*out = make([]VirtualHost, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.WebAuthnSettings != nil {
		in, out := &in.WebAuthnSettings, &out.WebAuthnSettings
		*out = new(WebAuthnSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.WebProtectionSettings != nil {
		in, out := &in.WebProtectionSettings, &out.WebProtectionSettings
		*out = new(WebProtectionSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Domain.
func (in *Domain) DeepCopy() *Domain {
	if in == nil {
		return nil
	}
	out := new(Domain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormField) DeepCopyInto(out *FormField) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormField.
func (in *FormField) DeepCopy() *FormField {
	if in == nil {
		return nil
	}
	out := new(FormField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyRetrievalSettings) DeepCopyInto(out *KeyRetrievalSettings) {
	*out = *in
	if in.AllowPrivateIpAddress != nil {
		in, out := &in.AllowPrivateIpAddress, &out.AllowPrivateIpAddress
		*out = new(bool)
		**out = **in
	}
	if in.AllowUnsecuredHttpUri != nil {
		in, out := &in.AllowUnsecuredHttpUri, &out.AllowUnsecuredHttpUri
		*out = new(bool)
		**out = **in
	}
	if in.CacheMaxEntries != nil {
		in, out := &in.CacheMaxEntries, &out.CacheMaxEntries
		*out = new(int32)
		**out = **in
	}
	if in.CacheTtlSeconds != nil {
		in, out := &in.CacheTtlSeconds, &out.CacheTtlSeconds
		*out = new(int32)
		**out = **in
	}
	if in.FetchTimeoutMs != nil {
		in, out := &in.FetchTimeoutMs, &out.FetchTimeoutMs
		*out = new(int32)
		**out = **in
	}
	if in.MaxResponseSizeKb != nil {
		in, out := &in.MaxResponseSizeKb, &out.MaxResponseSizeKb
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyRetrievalSettings.
func (in *KeyRetrievalSettings) DeepCopy() *KeyRetrievalSettings {
	if in == nil {
		return nil
	}
	out := new(KeyRetrievalSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginSettings) DeepCopyInto(out *LoginSettings) {
	*out = *in
	if in.CertificateBasedAuthEnabled != nil {
		in, out := &in.CertificateBasedAuthEnabled, &out.CertificateBasedAuthEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CertificateBasedAuthUrl != nil {
		in, out := &in.CertificateBasedAuthUrl, &out.CertificateBasedAuthUrl
		*out = new(string)
		**out = **in
	}
	if in.ForgotPasswordEnabled != nil {
		in, out := &in.ForgotPasswordEnabled, &out.ForgotPasswordEnabled
		*out = new(bool)
		**out = **in
	}
	if in.HideForm != nil {
		in, out := &in.HideForm, &out.HideForm
		*out = new(bool)
		**out = **in
	}
	if in.IdentifierFirstEnabled != nil {
		in, out := &in.IdentifierFirstEnabled, &out.IdentifierFirstEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Inherited != nil {
		in, out := &in.Inherited, &out.Inherited
		*out = new(bool)
		**out = **in
	}
	if in.MagicLinkAuthEnabled != nil {
		in, out := &in.MagicLinkAuthEnabled, &out.MagicLinkAuthEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PasswordlessDeviceNamingEnabled != nil {
		in, out := &in.PasswordlessDeviceNamingEnabled, &out.PasswordlessDeviceNamingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PasswordlessEnabled != nil {
		in, out := &in.PasswordlessEnabled, &out.PasswordlessEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PasswordlessEnforcePasswordEnabled != nil {
		in, out := &in.PasswordlessEnforcePasswordEnabled, &out.PasswordlessEnforcePasswordEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PasswordlessEnforcePasswordMaxAge != nil {
		in, out := &in.PasswordlessEnforcePasswordMaxAge, &out.PasswordlessEnforcePasswordMaxAge
		*out = new(int32)
		**out = **in
	}
	if in.PasswordlessRememberDeviceEnabled != nil {
		in, out := &in.PasswordlessRememberDeviceEnabled, &out.PasswordlessRememberDeviceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.RegisterEnabled != nil {
		in, out := &in.RegisterEnabled, &out.RegisterEnabled
		*out = new(bool)
		**out = **in
	}
	if in.RememberMeEnabled != nil {
		in, out := &in.RememberMeEnabled, &out.RememberMeEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ResetPasswordOnExpiration != nil {
		in, out := &in.ResetPasswordOnExpiration, &out.ResetPasswordOnExpiration
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginSettings.
func (in *LoginSettings) DeepCopy() *LoginSettings {
	if in == nil {
		return nil
	}
	out := new(LoginSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OidcSettings) DeepCopyInto(out *OidcSettings) {
	*out = *in
	if in.CibaSettings != nil {
		in, out := &in.CibaSettings, &out.CibaSettings
		*out = new(CIBASettings)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientRegistrationSettings != nil {
		in, out := &in.ClientRegistrationSettings, &out.ClientRegistrationSettings
		*out = new(ClientRegistrationSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.PostLogoutRedirectUris != nil {
		in, out := &in.PostLogoutRedirectUris, &out.PostLogoutRedirectUris
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.RedirectUriStrictMatching != nil {
		in, out := &in.RedirectUriStrictMatching, &out.RedirectUriStrictMatching
		*out = new(bool)
		**out = **in
	}
	if in.RequestUris != nil {
		in, out := &in.RequestUris, &out.RequestUris
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.SecurityProfileSettings != nil {
		in, out := &in.SecurityProfileSettings, &out.SecurityProfileSettings
		*out = new(SecurityProfileSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OidcSettings.
func (in *OidcSettings) DeepCopy() *OidcSettings {
	if in == nil {
		return nil
	}
	out := new(OidcSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordSettings) DeepCopyInto(out *PasswordSettings) {
	*out = *in
	if in.ExcludePasswordsInDictionary != nil {
		in, out := &in.ExcludePasswordsInDictionary, &out.ExcludePasswordsInDictionary
		*out = new(bool)
		**out = **in
	}
	if in.ExcludeUserProfileInfoInPassword != nil {
		in, out := &in.ExcludeUserProfileInfoInPassword, &out.ExcludeUserProfileInfoInPassword
		*out = new(bool)
		**out = **in
	}
	if in.ExpiryDuration != nil {
		in, out := &in.ExpiryDuration, &out.ExpiryDuration
		*out = new(int32)
		**out = **in
	}
	if in.IncludeNumbers != nil {
		in, out := &in.IncludeNumbers, &out.IncludeNumbers
		*out = new(bool)
		**out = **in
	}
	if in.IncludeSpecialCharacters != nil {
		in, out := &in.IncludeSpecialCharacters, &out.IncludeSpecialCharacters
		*out = new(bool)
		**out = **in
	}
	if in.Inherited != nil {
		in, out := &in.Inherited, &out.Inherited
		*out = new(bool)
		**out = **in
	}
	if in.LettersInMixedCase != nil {
		in, out := &in.LettersInMixedCase, &out.LettersInMixedCase
		*out = new(bool)
		**out = **in
	}
	if in.MaxConsecutiveLetters != nil {
		in, out := &in.MaxConsecutiveLetters, &out.MaxConsecutiveLetters
		*out = new(int32)
		**out = **in
	}
	if in.MaxLength != nil {
		in, out := &in.MaxLength, &out.MaxLength
		*out = new(int32)
		**out = **in
	}
	if in.MinLength != nil {
		in, out := &in.MinLength, &out.MinLength
		*out = new(int32)
		**out = **in
	}
	if in.OldPasswords != nil {
		in, out := &in.OldPasswords, &out.OldPasswords
		*out = new(int32)
		**out = **in
	}
	if in.PasswordHistoryEnabled != nil {
		in, out := &in.PasswordHistoryEnabled, &out.PasswordHistoryEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordSettings.
func (in *PasswordSettings) DeepCopy() *PasswordSettings {
	if in == nil {
		return nil
	}
	out := new(PasswordSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResetPasswordSettings) DeepCopyInto(out *ResetPasswordSettings) {
	*out = *in
	if in.OldPasswordRequired != nil {
		in, out := &in.OldPasswordRequired, &out.OldPasswordRequired
		*out = new(bool)
		**out = **in
	}
	if in.TokenAge != nil {
		in, out := &in.TokenAge, &out.TokenAge
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResetPasswordSettings.
func (in *ResetPasswordSettings) DeepCopy() *ResetPasswordSettings {
	if in == nil {
		return nil
	}
	out := new(ResetPasswordSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SCIMSettings) DeepCopyInto(out *SCIMSettings) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.IdpSelectionEnabled != nil {
		in, out := &in.IdpSelectionEnabled, &out.IdpSelectionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IdpSelectionRule != nil {
		in, out := &in.IdpSelectionRule, &out.IdpSelectionRule
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SCIMSettings.
func (in *SCIMSettings) DeepCopy() *SCIMSettings {
	if in == nil {
		return nil
	}
	out := new(SCIMSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SamlSettings) DeepCopyInto(out *SamlSettings) {
	*out = *in
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EntityId != nil {
		in, out := &in.EntityId, &out.EntityId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SamlSettings.
func (in *SamlSettings) DeepCopy() *SamlSettings {
	if in == nil {
		return nil
	}
	out := new(SamlSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretExpirationSettings) DeepCopyInto(out *SecretExpirationSettings) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExpiryTimeSeconds != nil {
		in, out := &in.ExpiryTimeSeconds, &out.ExpiryTimeSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretExpirationSettings.
func (in *SecretExpirationSettings) DeepCopy() *SecretExpirationSettings {
	if in == nil {
		return nil
	}
	out := new(SecretExpirationSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityProfileSettings) DeepCopyInto(out *SecurityProfileSettings) {
	*out = *in
	if in.EnableFapiBrazil != nil {
		in, out := &in.EnableFapiBrazil, &out.EnableFapiBrazil
		*out = new(bool)
		**out = **in
	}
	if in.EnablePlainFapi != nil {
		in, out := &in.EnablePlainFapi, &out.EnablePlainFapi
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityProfileSettings.
func (in *SecurityProfileSettings) DeepCopy() *SecurityProfileSettings {
	if in == nil {
		return nil
	}
	out := new(SecurityProfileSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfServiceAccountManagementSettings) DeepCopyInto(out *SelfServiceAccountManagementSettings) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ResetPassword != nil {
		in, out := &in.ResetPassword, &out.ResetPassword
		*out = new(ResetPasswordSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfServiceAccountManagementSettings.
func (in *SelfServiceAccountManagementSettings) DeepCopy() *SelfServiceAccountManagementSettings {
	if in == nil {
		return nil
	}
	out := new(SelfServiceAccountManagementSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Errors.DeepCopyInto(&out.Errors)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenExchangeSettings) DeepCopyInto(out *TokenExchangeSettings) {
	*out = *in
	if in.AllowDelegation != nil {
		in, out := &in.AllowDelegation, &out.AllowDelegation
		*out = new(bool)
		**out = **in
	}
	if in.AllowImpersonation != nil {
		in, out := &in.AllowImpersonation, &out.AllowImpersonation
		*out = new(bool)
		**out = **in
	}
	if in.AllowedActorTokenTypes != nil {
		in, out := &in.AllowedActorTokenTypes, &out.AllowedActorTokenTypes
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedRequestedTokenTypes != nil {
		in, out := &in.AllowedRequestedTokenTypes, &out.AllowedRequestedTokenTypes
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.AllowedSubjectTokenTypes != nil {
		in, out := &in.AllowedSubjectTokenTypes, &out.AllowedSubjectTokenTypes
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MaxDelegationDepth != nil {
		in, out := &in.MaxDelegationDepth, &out.MaxDelegationDepth
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenExchangeSettings.
func (in *TokenExchangeSettings) DeepCopy() *TokenExchangeSettings {
	if in == nil {
		return nil
	}
	out := new(TokenExchangeSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UMASettings) DeepCopyInto(out *UMASettings) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UMASettings.
func (in *UMASettings) DeepCopy() *UMASettings {
	if in == nil {
		return nil
	}
	out := new(UMASettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualHost) DeepCopyInto(out *VirtualHost) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.OverrideEntrypoint != nil {
		in, out := &in.OverrideEntrypoint, &out.OverrideEntrypoint
		*out = new(bool)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualHost.
func (in *VirtualHost) DeepCopy() *VirtualHost {
	if in == nil {
		return nil
	}
	out := new(VirtualHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebAuthnSettings) DeepCopyInto(out *WebAuthnSettings) {
	*out = *in
	if in.AttestationConveyancePreference != nil {
		in, out := &in.AttestationConveyancePreference, &out.AttestationConveyancePreference
		*out = new(string)
		**out = **in
	}
	if in.AuthenticatorAttachment != nil {
		in, out := &in.AuthenticatorAttachment, &out.AuthenticatorAttachment
		*out = new(string)
		**out = **in
	}
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
	if in.EnforceAuthenticatorIntegrity != nil {
		in, out := &in.EnforceAuthenticatorIntegrity, &out.EnforceAuthenticatorIntegrity
		*out = new(bool)
		**out = **in
	}
	if in.EnforceAuthenticatorIntegrityMaxAge != nil {
		in, out := &in.EnforceAuthenticatorIntegrityMaxAge, &out.EnforceAuthenticatorIntegrityMaxAge
		*out = new(int32)
		**out = **in
	}
	if in.ForceRegistration != nil {
		in, out := &in.ForceRegistration, &out.ForceRegistration
		*out = new(bool)
		**out = **in
	}
	if in.Origin != nil {
		in, out := &in.Origin, &out.Origin
		*out = new(string)
		**out = **in
	}
	if in.RelyingPartyId != nil {
		in, out := &in.RelyingPartyId, &out.RelyingPartyId
		*out = new(string)
		**out = **in
	}
	if in.RelyingPartyName != nil {
		in, out := &in.RelyingPartyName, &out.RelyingPartyName
		*out = new(string)
		**out = **in
	}
	if in.RequireResidentKey != nil {
		in, out := &in.RequireResidentKey, &out.RequireResidentKey
		*out = new(bool)
		**out = **in
	}
	if in.UserVerification != nil {
		in, out := &in.UserVerification, &out.UserVerification
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebAuthnSettings.
func (in *WebAuthnSettings) DeepCopy() *WebAuthnSettings {
	if in == nil {
		return nil
	}
	out := new(WebAuthnSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebProtectionSettings) DeepCopyInto(out *WebProtectionSettings) {
	*out = *in
	if in.Csp != nil {
		in, out := &in.Csp, &out.Csp
		*out = new(CspSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Xframe != nil {
		in, out := &in.Xframe, &out.Xframe
		*out = new(XFrameSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Xss != nil {
		in, out := &in.Xss, &out.Xss
		*out = new(XssProtectionSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebProtectionSettings.
func (in *WebProtectionSettings) DeepCopy() *WebProtectionSettings {
	if in == nil {
		return nil
	}
	out := new(WebProtectionSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XFrameSettings) DeepCopyInto(out *XFrameSettings) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Inherited != nil {
		in, out := &in.Inherited, &out.Inherited
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XFrameSettings.
func (in *XFrameSettings) DeepCopy() *XFrameSettings {
	if in == nil {
		return nil
	}
	out := new(XFrameSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XssProtectionSettings) DeepCopyInto(out *XssProtectionSettings) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Inherited != nil {
		in, out := &in.Inherited, &out.Inherited
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XssProtectionSettings.
func (in *XssProtectionSettings) DeepCopy() *XssProtectionSettings {
	if in == nil {
		return nil
	}
	out := new(XssProtectionSettings)
	in.DeepCopyInto(out)
	return out
}
