//go:build !ignore_autogenerated

/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package portaltheme

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Background) DeepCopyInto(out *Background) {
	*out = *in
	if in.Page != nil {
		in, out := &in.Page, &out.Page
		*out = new(string)
		**out = **in
	}
	if in.Card != nil {
		in, out := &in.Card, &out.Card
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Background.
func (in *Background) DeepCopy() *Background {
	if in == nil {
		return nil
	}
	out := new(Background)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Color) DeepCopyInto(out *Color) {
	*out = *in
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(string)
		**out = **in
	}
	if in.Secondary != nil {
		in, out := &in.Secondary, &out.Secondary
		*out = new(string)
		**out = **in
	}
	if in.Tertiary != nil {
		in, out := &in.Tertiary, &out.Tertiary
		*out = new(string)
		**out = **in
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(string)
		**out = **in
	}
	if in.Background != nil {
		in, out := &in.Background, &out.Background
		*out = new(Background)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Color.
func (in *Color) DeepCopy() *Color {
	if in == nil {
		return nil
	}
	out := new(Color)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Definition) DeepCopyInto(out *Definition) {
	*out = *in
	if in.CustomCss != nil {
		in, out := &in.CustomCss, &out.CustomCss
		*out = new(string)
		**out = **in
	}
	if in.Font != nil {
		in, out := &in.Font, &out.Font
		*out = new(Font)
		(*in).DeepCopyInto(*out)
	}
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(Color)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Definition.
func (in *Definition) DeepCopy() *Definition {
	if in == nil {
		return nil
	}
	out := new(Definition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Font) DeepCopyInto(out *Font) {
	*out = *in
	if in.FontFamily != nil {
		in, out := &in.FontFamily, &out.FontFamily
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Font.
func (in *Font) DeepCopy() *Font {
	if in == nil {
		return nil
	}
	out := new(Font)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Status) DeepCopyInto(out *Status) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Errors.DeepCopyInto(&out.Errors)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Status.
func (in *Status) DeepCopy() *Status {
	if in == nil {
		return nil
	}
	out := new(Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Type) DeepCopyInto(out *Type) {
	*out = *in
	in.Definition.DeepCopyInto(&out.Definition)
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(string)
		**out = **in
	}
	if in.OptionalLogo != nil {
		in, out := &in.OptionalLogo, &out.OptionalLogo
		*out = new(string)
		**out = **in
	}
	if in.Favicon != nil {
		in, out := &in.Favicon, &out.Favicon
		*out = new(string)
		**out = **in
	}
	if in.BackgroundImage != nil {
		in, out := &in.BackgroundImage, &out.BackgroundImage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Type.
func (in *Type) DeepCopy() *Type {
	if in == nil {
		return nil
	}
	out := new(Type)
	in.DeepCopyInto(out)
	return out
}
