// Package certificate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package certificate

import (
	"github.com/gravitee-io/gravitee-kubernetes-operator/api/model/refs"
	"github.com/gravitee-io/gravitee-kubernetes-operator/api/model/utils"
)

// AutomationCertificate A certificate managed under a domain by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update.
// +kubebuilder:validation:XValidation:rule="(has(self.system) && self.system) || (has(self.name) && has(self.type) && has(self.configuration))",message="name, type and configuration are required unless system is true"
// +kubebuilder:validation:XValidation:rule="has(self.type) == has(oldSelf.type) && (!has(self.type) || self.type == oldSelf.type)",message="type is immutable"
type AutomationCertificate = Certificate

// Certificate A certificate managed under a domain by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update.
// +kubebuilder:validation:XValidation:rule="(has(self.system) && self.system) || (has(self.name) && has(self.type) && has(self.configuration))",message="name, type and configuration are required unless system is true"
// +kubebuilder:validation:XValidation:rule="has(self.type) == has(oldSelf.type) && (!has(self.type) || self.type == oldSelf.type)",message="type is immutable"
type Certificate struct {
	// Configuration Plugin-specific configuration, a free-form object sent to AM as a JSON string. The keystore file field (`jks` or `content`) is a JSON string `{"name":"...","content":"<base64>"}`.
	// +kubebuilder:validation:Optional
	Configuration *utils.GenericStringMap `json:"configuration,omitempty"`

	// DomainRef Domain CRD reference
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="domainRef is immutable"
	// +kubebuilder:validation:XValidation:rule="size(self.name) > 0",message="domainRef.name must not be empty"
	DomainRef refs.NamespacedName `json:"domainRef"`

	// Name Human-readable name of the certificate.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=255
	Name *string `json:"name,omitempty"`

	// System Whether this is the domain's system certificate. Immutable after creation. When true, only key is required; the certificate is built from the domains.certificates.default.* system settings and the name, type, and configuration fields are ignored.
	// +kubebuilder:validation:Optional
	// Defaults to false.
	// +kubebuilder:default=false
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="system is immutable"
	System *bool `json:"system,omitempty"`

	// Type Certificate plugin type identifier. Immutable after creation.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:MinLength=1
	Type *string `json:"type,omitempty"`
}
