//go:build !ignore_autogenerated

/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package gateway

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraviteeConfig) DeepCopyInto(out *GraviteeConfig) {
	*out = *in
	if in.YAML != nil {
		in, out := &in.YAML, &out.YAML
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraviteeConfig.
func (in *GraviteeConfig) DeepCopy() *GraviteeConfig {
	if in == nil {
		return nil
	}
	out := new(GraviteeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraviteeGateway) DeepCopyInto(out *GraviteeGateway) {
	*out = *in
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]GraviteeListener, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gravitee != nil {
		in, out := &in.Gravitee, &out.Gravitee
		*out = new(GraviteeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(KubernetesConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraviteeGateway.
func (in *GraviteeGateway) DeepCopy() *GraviteeGateway {
	if in == nil {
		return nil
	}
	out := new(GraviteeGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraviteeListener) DeepCopyInto(out *GraviteeListener) {
	*out = *in
	in.Listener.DeepCopyInto(&out.Listener)
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(GraviteeListenerConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraviteeListener.
func (in *GraviteeListener) DeepCopy() *GraviteeListener {
	if in == nil {
		return nil
	}
	out := new(GraviteeListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraviteeListenerConfig) DeepCopyInto(out *GraviteeListenerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraviteeListenerConfig.
func (in *GraviteeListenerConfig) DeepCopy() *GraviteeListenerConfig {
	if in == nil {
		return nil
	}
	out := new(GraviteeListenerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraviteeListenerTLSConfig) DeepCopyInto(out *GraviteeListenerTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraviteeListenerTLSConfig.
func (in *GraviteeListenerTLSConfig) DeepCopy() *GraviteeListenerTLSConfig {
	if in == nil {
		return nil
	}
	out := new(GraviteeListenerTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesConfig) DeepCopyInto(out *KubernetesConfig) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	in.Service.DeepCopyInto(&out.Service)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesConfig.
func (in *KubernetesConfig) DeepCopy() *KubernetesConfig {
	if in == nil {
		return nil
	}
	out := new(KubernetesConfig)
	in.DeepCopyInto(out)
	return out
}
