# Copyright (C) 2015 The Gravitee team (http://gravitee.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Trigger E2E

on:
  workflow_dispatch:
    inputs:
      pipeline-branch:
        description: "CircleCI pipeline branch"
        required: false
        default: ""
        type: string
jobs:
  trigger-test-suite:
    runs-on: ubuntu-latest
    env:
      CIRCLECI_TOKEN: ${{ secrets.CIRCLECI_TOKEN }}
      PIPELINE_BRANCH: ${{ inputs.pipeline-branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Trigger E2E pipeline"
        run: |
          echo "🧪 Triggering E2E test pipeline"
          npx zx hack/scripts/trigger-e2e-test.mjs --notify true --pipeline-branch ${PIPELINE_BRANCH}
